package com.atakmap.android.uastool.generic;

import android.os.Parcel;
import android.os.Parcelable;
import com.atakmap.android.uastool.tasks.route.UASPoint;
import com.atakmap.coremap.log.Log;
import java.util.ArrayList;
import java.util.Arrays;

public class IAircraftItem implements Parcelable {
    public static final Parcelable.Creator<IAircraftItem> CREATOR = new Parcelable.Creator<IAircraftItem>() {
        public IAircraftItem createFromParcel(Parcel parcel) {
            return new IAircraftItem(parcel);
        }

        public IAircraftItem[] newArray(int i) {
            return new IAircraftItem[i];
        }
    };
    public static final String TAG = "IAircraftItem";
    public String UID;
    public double acalt;
    public double acce;
    public double achal;
    public double acheading;
    public double aclat;
    public double acle;
    public double aclon;
    public boolean activeRoute;
    public boolean areMotorsOn;
    public double attitudePitch;
    public double attitudeRoll;
    public double attitudeYaw;
    public int battMax;
    public int battRem;
    public double battVolt;
    public String callsign;
    public double climbRate;
    public int flightTime;
    public int flightTimeRemaining;
    public boolean getThermal;
    public int goHomeBatteryPercent;
    public boolean hasGPS;
    public double homealt;
    public double homelat;
    public double homelon;
    public boolean isFlying;
    public String platformId;
    public ArrayList<UASPoint> routePoints;
    public double sensorAzimuth;
    public double sensorElevation;
    public double sensorHFOV;
    public String sensorModel;
    public double sensorNorth;
    public double sensorRange;
    public double sensorRoll;
    public double sensorVFOV;
    public int signalQuality;
    public double slope;
    public double speed;
    public double spinPitch;
    public double spinRoll;
    public double spinYaw;
    public double[] spoiBounds;
    public double spoialt;
    public double spoilat;
    public double spoilon;

    public int describeContents() {
        return 0;
    }

    public IAircraftItem() {
        this.routePoints = new ArrayList<>();
        this.aclat = Double.NaN;
        this.aclon = Double.NaN;
        this.acalt = Double.NaN;
        this.achal = Double.NaN;
        this.acce = Double.NaN;
        this.acle = Double.NaN;
        this.acheading = Double.NaN;
        this.spoilat = Double.NaN;
        this.spoilon = Double.NaN;
        this.spoialt = Double.NaN;
        initSpoiViewBounds();
        this.homelat = Double.NaN;
        this.homelon = Double.NaN;
        this.homealt = Double.NaN;
        this.speed = Double.NaN;
        this.slope = Double.NaN;
        this.sensorAzimuth = Double.NaN;
        this.sensorElevation = Double.NaN;
        this.sensorRange = Double.NaN;
        this.sensorRoll = Double.NaN;
        this.sensorHFOV = Double.NaN;
        this.sensorVFOV = Double.NaN;
        this.sensorNorth = Double.NaN;
        this.battVolt = Double.NaN;
        this.climbRate = Double.NaN;
        this.attitudePitch = Double.NaN;
        this.attitudeRoll = Double.NaN;
        this.attitudeYaw = Double.NaN;
        this.spinPitch = Double.NaN;
        this.spinRoll = Double.NaN;
        this.spinYaw = Double.NaN;
        this.battMax = Integer.MIN_VALUE;
        this.battRem = Integer.MIN_VALUE;
        this.signalQuality = Integer.MIN_VALUE;
        this.flightTime = Integer.MIN_VALUE;
        this.goHomeBatteryPercent = Integer.MIN_VALUE;
        this.flightTimeRemaining = Integer.MIN_VALUE;
        this.hasGPS = false;
        this.areMotorsOn = false;
        this.isFlying = false;
        this.getThermal = false;
        this.UID = null;
        this.callsign = null;
        this.sensorModel = null;
        this.activeRoute = false;
        this.platformId = "generic";
    }

    public void initSpoiViewBounds() {
        double[] dArr = this.spoiBounds;
        if (dArr == null || dArr.length < 8) {
            Log.d(TAG, "Creating new SpoiViewBounds");
            this.spoiBounds = new double[8];
        }
        Arrays.fill(this.spoiBounds, Double.NaN);
    }

    public IAircraftItem(Parcel parcel) {
        this();
        this.aclat = parcel.readDouble();
        this.aclon = parcel.readDouble();
        this.acalt = parcel.readDouble();
        this.achal = parcel.readDouble();
        this.acce = parcel.readDouble();
        this.acle = parcel.readDouble();
        this.acheading = parcel.readDouble();
        this.spoilat = parcel.readDouble();
        this.spoilon = parcel.readDouble();
        this.spoialt = parcel.readDouble();
        parcel.readDoubleArray(this.spoiBounds);
        this.homelat = parcel.readDouble();
        this.homelon = parcel.readDouble();
        this.homealt = parcel.readDouble();
        this.speed = parcel.readDouble();
        this.slope = parcel.readDouble();
        this.sensorAzimuth = parcel.readDouble();
        this.sensorElevation = parcel.readDouble();
        this.sensorRange = parcel.readDouble();
        this.sensorRoll = parcel.readDouble();
        this.sensorHFOV = parcel.readDouble();
        this.sensorVFOV = parcel.readDouble();
        this.sensorNorth = parcel.readDouble();
        this.battVolt = parcel.readDouble();
        this.climbRate = parcel.readDouble();
        this.attitudePitch = parcel.readDouble();
        this.attitudeRoll = parcel.readDouble();
        this.attitudeYaw = parcel.readDouble();
        this.spinPitch = parcel.readDouble();
        this.spinRoll = parcel.readDouble();
        this.spinYaw = parcel.readDouble();
        this.battMax = parcel.readInt();
        this.battRem = parcel.readInt();
        this.signalQuality = parcel.readInt();
        this.flightTime = parcel.readInt();
        this.goHomeBatteryPercent = parcel.readInt();
        this.flightTimeRemaining = parcel.readInt();
        boolean z = false;
        this.hasGPS = parcel.readInt() == 1;
        this.areMotorsOn = parcel.readInt() == 1;
        this.isFlying = parcel.readInt() == 1;
        this.getThermal = parcel.readInt() == 1 ? true : z;
        this.UID = parcel.readString();
        this.callsign = parcel.readString();
        this.sensorModel = parcel.readString();
        this.platformId = parcel.readString();
        parcel.readTypedList(this.routePoints, UASPoint.CREATOR);
    }

    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeDouble(this.aclat);
        parcel.writeDouble(this.aclon);
        parcel.writeDouble(this.acalt);
        parcel.writeDouble(this.achal);
        parcel.writeDouble(this.acce);
        parcel.writeDouble(this.acle);
        parcel.writeDouble(this.acheading);
        parcel.writeDouble(this.spoilat);
        parcel.writeDouble(this.spoilon);
        parcel.writeDouble(this.spoialt);
        parcel.writeDoubleArray(this.spoiBounds);
        parcel.writeDouble(this.homelat);
        parcel.writeDouble(this.homelon);
        parcel.writeDouble(this.homealt);
        parcel.writeDouble(this.speed);
        parcel.writeDouble(this.slope);
        parcel.writeDouble(this.sensorAzimuth);
        parcel.writeDouble(this.sensorElevation);
        parcel.writeDouble(this.sensorRange);
        parcel.writeDouble(this.sensorRoll);
        parcel.writeDouble(this.sensorHFOV);
        parcel.writeDouble(this.sensorVFOV);
        parcel.writeDouble(this.sensorNorth);
        parcel.writeDouble(this.battVolt);
        parcel.writeDouble(this.climbRate);
        parcel.writeDouble(this.attitudePitch);
        parcel.writeDouble(this.attitudeRoll);
        parcel.writeDouble(this.attitudeYaw);
        parcel.writeDouble(this.spinPitch);
        parcel.writeDouble(this.spinRoll);
        parcel.writeDouble(this.spinYaw);
        parcel.writeInt(this.battMax);
        parcel.writeInt(this.battRem);
        parcel.writeInt(this.signalQuality);
        parcel.writeInt(this.flightTime);
        parcel.writeInt(this.goHomeBatteryPercent);
        parcel.writeInt(this.flightTimeRemaining);
        parcel.writeInt(this.hasGPS ? 1 : 0);
        parcel.writeInt(this.areMotorsOn ? 1 : 0);
        parcel.writeInt(this.isFlying ? 1 : 0);
        parcel.writeInt(this.getThermal ? 1 : 0);
        parcel.writeString(this.UID);
        parcel.writeString(this.callsign);
        parcel.writeString(this.sensorModel);
        parcel.writeString(this.platformId);
        parcel.writeTypedList(this.routePoints);
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("aclat: ");
        sb.append(this.aclat);
        sb.append(" aclon: ");
        sb.append(this.aclon);
        sb.append(" acalt: ");
        sb.append(this.acalt);
        sb.append(" achal: ");
        sb.append(this.achal);
        sb.append(" acce: ");
        sb.append(this.acce);
        sb.append(" acle: ");
        sb.append(this.acle);
        sb.append(" acheading: ");
        sb.append(this.acheading);
        sb.append(" spoilat: ");
        sb.append(this.spoilat);
        sb.append(" spoilon: ");
        sb.append(this.spoilon);
        sb.append(" spoialt: ");
        sb.append(this.spoialt);
        sb.append(" SpoiBounds : (");
        for (double append : this.spoiBounds) {
            sb.append(append);
            sb.append(",");
        }
        sb.append(")");
        sb.append(" homelat: ");
        sb.append(this.homelat);
        sb.append(" homelon: ");
        sb.append(this.homelon);
        sb.append(" homealt: ");
        sb.append(this.homealt);
        sb.append(" speed: ");
        sb.append(this.speed);
        sb.append(" slope: ");
        sb.append(this.slope);
        sb.append(" sensorAzimuth: ");
        sb.append(this.sensorAzimuth);
        sb.append(" sensorElevation: ");
        sb.append(this.sensorElevation);
        sb.append(" sensorRange: ");
        sb.append(this.sensorRange);
        sb.append(" sensorRoll: ");
        sb.append(this.sensorRoll);
        sb.append(" sensorHFOV: ");
        sb.append(this.sensorHFOV);
        sb.append(" sensorVFOV: ");
        sb.append(this.sensorVFOV);
        sb.append(" sensorNorth: ");
        sb.append(this.sensorNorth);
        sb.append(" battVolt: ");
        sb.append(this.battVolt);
        sb.append(" climbRate: ");
        sb.append(this.climbRate);
        sb.append(" attitudePitch: ");
        sb.append(this.attitudePitch);
        sb.append(" attitudeRoll: ");
        sb.append(this.attitudeRoll);
        sb.append(" attitudeYaw: ");
        sb.append(this.attitudeYaw);
        sb.append(" spinPitch: ");
        sb.append(this.spinPitch);
        sb.append(" spinRoll: ");
        sb.append(this.spinRoll);
        sb.append(" spinYaw: ");
        sb.append(this.spinYaw);
        sb.append(" battMax: ");
        sb.append(this.battMax);
        sb.append(" battRem: ");
        sb.append(this.battRem);
        sb.append(" signalQuality: ");
        sb.append(this.signalQuality);
        sb.append(" flightTime: ");
        sb.append(this.flightTime);
        sb.append(" goHomeBatteryPercent: ");
        sb.append(this.goHomeBatteryPercent);
        sb.append(" flightTimeRemaining: ");
        sb.append(this.flightTimeRemaining);
        sb.append(" hasGPS: ");
        sb.append(this.hasGPS);
        sb.append(" areMotorsOn: ");
        sb.append(this.areMotorsOn);
        sb.append(" isFlying: ");
        sb.append(this.isFlying);
        sb.append(" getThermal: ");
        sb.append(this.getThermal);
        sb.append(" UID: ");
        sb.append(this.UID);
        sb.append(" callsign: ");
        sb.append(this.callsign);
        sb.append(" sensorModel: ");
        sb.append(this.sensorModel);
        sb.append(" platformId: ");
        sb.append(this.platformId);
        sb.append(" activeRoute: ");
        sb.append(this.activeRoute);
        return sb.toString();
    }

    public IAircraftItem copy() {
        IAircraftItem iAircraftItem = new IAircraftItem();
        iAircraftItem.aclat = this.aclat;
        iAircraftItem.aclon = this.aclon;
        iAircraftItem.acalt = this.acalt;
        iAircraftItem.achal = this.achal;
        iAircraftItem.acce = this.acce;
        iAircraftItem.acle = this.acle;
        iAircraftItem.acheading = this.acheading;
        iAircraftItem.spoilat = this.spoilat;
        iAircraftItem.spoilon = this.spoilon;
        iAircraftItem.spoialt = this.spoialt;
        iAircraftItem.spoiBounds = (double[]) this.spoiBounds.clone();
        iAircraftItem.homelat = this.homelat;
        iAircraftItem.homelon = this.homelon;
        iAircraftItem.homealt = this.homealt;
        iAircraftItem.speed = this.speed;
        iAircraftItem.slope = this.slope;
        iAircraftItem.sensorAzimuth = this.sensorAzimuth;
        iAircraftItem.sensorElevation = this.sensorElevation;
        iAircraftItem.sensorRange = this.sensorRange;
        iAircraftItem.sensorRoll = this.sensorRoll;
        iAircraftItem.sensorHFOV = this.sensorHFOV;
        iAircraftItem.sensorVFOV = this.sensorVFOV;
        iAircraftItem.sensorNorth = this.sensorNorth;
        iAircraftItem.battVolt = this.battVolt;
        iAircraftItem.climbRate = this.climbRate;
        iAircraftItem.attitudePitch = this.attitudePitch;
        iAircraftItem.attitudeRoll = this.attitudeRoll;
        iAircraftItem.attitudeYaw = this.attitudeYaw;
        iAircraftItem.spinPitch = this.spinPitch;
        iAircraftItem.spinRoll = this.spinRoll;
        iAircraftItem.spinYaw = this.spinYaw;
        iAircraftItem.battMax = this.battMax;
        iAircraftItem.battRem = this.battRem;
        iAircraftItem.signalQuality = this.signalQuality;
        iAircraftItem.flightTime = this.signalQuality;
        iAircraftItem.goHomeBatteryPercent = this.goHomeBatteryPercent;
        iAircraftItem.flightTimeRemaining = this.flightTimeRemaining;
        iAircraftItem.hasGPS = this.hasGPS;
        iAircraftItem.areMotorsOn = this.areMotorsOn;
        iAircraftItem.isFlying = this.isFlying;
        iAircraftItem.getThermal = this.getThermal;
        iAircraftItem.UID = this.UID;
        iAircraftItem.callsign = this.callsign;
        iAircraftItem.sensorModel = this.sensorModel;
        iAircraftItem.platformId = this.platformId;
        iAircraftItem.activeRoute = this.activeRoute;
        iAircraftItem.routePoints = (ArrayList) this.routePoints.clone();
        return iAircraftItem;
    }
}
