package com.trilliumeng.android.orion.orionsdklibrary;

/* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R */
public final class C5913R {

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$anim */
    public static final class anim {
        public static int abc_fade_in;
        public static int abc_fade_out;
        public static int abc_grow_fade_in_from_bottom;
        public static int abc_popup_enter;
        public static int abc_popup_exit;
        public static int abc_shrink_fade_out_from_bottom;
        public static int abc_slide_in_bottom;
        public static int abc_slide_in_top;
        public static int abc_slide_out_bottom;
        public static int abc_slide_out_top;
        public static int abc_tooltip_enter;
        public static int abc_tooltip_exit;
        public static int btn_checkbox_to_checked_box_inner_merged_animation;
        public static int btn_checkbox_to_checked_box_outer_merged_animation;
        public static int btn_checkbox_to_checked_icon_null_animation;
        public static int btn_checkbox_to_unchecked_box_inner_merged_animation;
        public static int btn_checkbox_to_unchecked_check_path_merged_animation;
        public static int btn_checkbox_to_unchecked_icon_null_animation;
        public static int btn_radio_to_off_mtrl_dot_group_animation;
        public static int btn_radio_to_off_mtrl_ring_outer_animation;
        public static int btn_radio_to_off_mtrl_ring_outer_path_animation;
        public static int btn_radio_to_on_mtrl_dot_group_animation;
        public static int btn_radio_to_on_mtrl_ring_outer_animation;
        public static int btn_radio_to_on_mtrl_ring_outer_path_animation;

        private anim() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$attr */
    public static final class attr {
        public static int actionBarDivider;
        public static int actionBarItemBackground;
        public static int actionBarPopupTheme;
        public static int actionBarSize;
        public static int actionBarSplitStyle;
        public static int actionBarStyle;
        public static int actionBarTabBarStyle;
        public static int actionBarTabStyle;
        public static int actionBarTabTextStyle;
        public static int actionBarTheme;
        public static int actionBarWidgetTheme;
        public static int actionButtonStyle;
        public static int actionDropDownStyle;
        public static int actionLayout;
        public static int actionMenuTextAppearance;
        public static int actionMenuTextColor;
        public static int actionModeBackground;
        public static int actionModeCloseButtonStyle;
        public static int actionModeCloseDrawable;
        public static int actionModeCopyDrawable;
        public static int actionModeCutDrawable;
        public static int actionModeFindDrawable;
        public static int actionModePasteDrawable;
        public static int actionModePopupWindowStyle;
        public static int actionModeSelectAllDrawable;
        public static int actionModeShareDrawable;
        public static int actionModeSplitBackground;
        public static int actionModeStyle;
        public static int actionModeWebSearchDrawable;
        public static int actionOverflowButtonStyle;
        public static int actionOverflowMenuStyle;
        public static int actionProviderClass;
        public static int actionViewClass;
        public static int activityChooserViewStyle;
        public static int alertDialogButtonGroupStyle;
        public static int alertDialogCenterButtons;
        public static int alertDialogStyle;
        public static int alertDialogTheme;
        public static int allowStacking;
        public static int alpha;
        public static int alphabeticModifiers;
        public static int arrowHeadLength;
        public static int arrowShaftLength;
        public static int autoCompleteTextViewStyle;
        public static int autoSizeMaxTextSize;
        public static int autoSizeMinTextSize;
        public static int autoSizePresetSizes;
        public static int autoSizeStepGranularity;
        public static int autoSizeTextType;
        public static int background;
        public static int backgroundSplit;
        public static int backgroundStacked;
        public static int backgroundTint;
        public static int backgroundTintMode;
        public static int barLength;
        public static int borderlessButtonStyle;
        public static int buttonBarButtonStyle;
        public static int buttonBarNegativeButtonStyle;
        public static int buttonBarNeutralButtonStyle;
        public static int buttonBarPositiveButtonStyle;
        public static int buttonBarStyle;
        public static int buttonCompat;
        public static int buttonGravity;
        public static int buttonIconDimen;
        public static int buttonPanelSideLayout;
        public static int buttonStyle;
        public static int buttonStyleSmall;
        public static int buttonTint;
        public static int buttonTintMode;
        public static int checkboxStyle;
        public static int checkedTextViewStyle;
        public static int closeIcon;
        public static int closeItemLayout;
        public static int collapseContentDescription;
        public static int collapseIcon;
        public static int color;
        public static int colorAccent;
        public static int colorBackgroundFloating;
        public static int colorButtonNormal;
        public static int colorControlActivated;
        public static int colorControlHighlight;
        public static int colorControlNormal;
        public static int colorError;
        public static int colorPrimary;
        public static int colorPrimaryDark;
        public static int colorSwitchThumbNormal;
        public static int commitIcon;
        public static int contentDescription;
        public static int contentInsetEnd;
        public static int contentInsetEndWithActions;
        public static int contentInsetLeft;
        public static int contentInsetRight;
        public static int contentInsetStart;
        public static int contentInsetStartWithNavigation;
        public static int controlBackground;
        public static int customNavigationLayout;
        public static int defaultQueryHint;
        public static int dialogCornerRadius;
        public static int dialogPreferredPadding;
        public static int dialogTheme;
        public static int displayOptions;
        public static int divider;
        public static int dividerHorizontal;
        public static int dividerPadding;
        public static int dividerVertical;
        public static int drawableBottomCompat;
        public static int drawableEndCompat;
        public static int drawableLeftCompat;
        public static int drawableRightCompat;
        public static int drawableSize;
        public static int drawableStartCompat;
        public static int drawableTint;
        public static int drawableTintMode;
        public static int drawableTopCompat;
        public static int drawerArrowStyle;
        public static int dropDownListViewStyle;
        public static int dropdownListPreferredItemHeight;
        public static int editTextBackground;
        public static int editTextColor;
        public static int editTextStyle;
        public static int elevation;
        public static int expandActivityOverflowButtonDrawable;
        public static int firstBaselineToTopHeight;
        public static int font;
        public static int fontFamily;
        public static int fontProviderAuthority;
        public static int fontProviderCerts;
        public static int fontProviderFetchStrategy;
        public static int fontProviderFetchTimeout;
        public static int fontProviderPackage;
        public static int fontProviderQuery;
        public static int fontStyle;
        public static int fontVariationSettings;
        public static int fontWeight;
        public static int gapBetweenBars;
        public static int goIcon;
        public static int height;
        public static int hideOnContentScroll;
        public static int homeAsUpIndicator;
        public static int homeLayout;
        public static int icon;
        public static int iconTint;
        public static int iconTintMode;
        public static int iconifiedByDefault;
        public static int imageButtonStyle;
        public static int indeterminateProgressStyle;
        public static int initialActivityCount;
        public static int isLightTheme;
        public static int itemPadding;
        public static int lastBaselineToBottomHeight;
        public static int layout;
        public static int lineHeight;
        public static int listChoiceBackgroundIndicator;
        public static int listChoiceIndicatorMultipleAnimated;
        public static int listChoiceIndicatorSingleAnimated;
        public static int listDividerAlertDialog;
        public static int listItemLayout;
        public static int listLayout;
        public static int listMenuViewStyle;
        public static int listPopupWindowStyle;
        public static int listPreferredItemHeight;
        public static int listPreferredItemHeightLarge;
        public static int listPreferredItemHeightSmall;
        public static int listPreferredItemPaddingEnd;
        public static int listPreferredItemPaddingLeft;
        public static int listPreferredItemPaddingRight;
        public static int listPreferredItemPaddingStart;
        public static int logo;
        public static int logoDescription;
        public static int maxButtonHeight;
        public static int measureWithLargestChild;
        public static int menu;
        public static int multiChoiceItemLayout;
        public static int navigationContentDescription;
        public static int navigationIcon;
        public static int navigationMode;
        public static int numericModifiers;
        public static int overlapAnchor;
        public static int paddingBottomNoButtons;
        public static int paddingEnd;
        public static int paddingStart;
        public static int paddingTopNoTitle;
        public static int panelBackground;
        public static int panelMenuListTheme;
        public static int panelMenuListWidth;
        public static int popupMenuStyle;
        public static int popupTheme;
        public static int popupWindowStyle;
        public static int preserveIconSpacing;
        public static int progressBarPadding;
        public static int progressBarStyle;
        public static int queryBackground;
        public static int queryHint;
        public static int radioButtonStyle;
        public static int ratingBarStyle;
        public static int ratingBarStyleIndicator;
        public static int ratingBarStyleSmall;
        public static int searchHintIcon;
        public static int searchIcon;
        public static int searchViewStyle;
        public static int seekBarStyle;
        public static int selectableItemBackground;
        public static int selectableItemBackgroundBorderless;
        public static int showAsAction;
        public static int showDividers;
        public static int showText;
        public static int showTitle;
        public static int singleChoiceItemLayout;
        public static int spinBars;
        public static int spinnerDropDownItemStyle;
        public static int spinnerStyle;
        public static int splitTrack;
        public static int srcCompat;
        public static int state_above_anchor;
        public static int subMenuArrow;
        public static int submitBackground;
        public static int subtitle;
        public static int subtitleTextAppearance;
        public static int subtitleTextColor;
        public static int subtitleTextStyle;
        public static int suggestionRowLayout;
        public static int switchMinWidth;
        public static int switchPadding;
        public static int switchStyle;
        public static int switchTextAppearance;
        public static int textAllCaps;
        public static int textAppearanceLargePopupMenu;
        public static int textAppearanceListItem;
        public static int textAppearanceListItemSecondary;
        public static int textAppearanceListItemSmall;
        public static int textAppearancePopupMenuHeader;
        public static int textAppearanceSearchResultSubtitle;
        public static int textAppearanceSearchResultTitle;
        public static int textAppearanceSmallPopupMenu;
        public static int textColorAlertDialogListItem;
        public static int textColorSearchUrl;
        public static int textLocale;
        public static int theme;
        public static int thickness;
        public static int thumbTextPadding;
        public static int thumbTint;
        public static int thumbTintMode;
        public static int tickMark;
        public static int tickMarkTint;
        public static int tickMarkTintMode;
        public static int tint;
        public static int tintMode;
        public static int title;
        public static int titleMargin;
        public static int titleMarginBottom;
        public static int titleMarginEnd;
        public static int titleMarginStart;
        public static int titleMarginTop;
        public static int titleMargins;
        public static int titleTextAppearance;
        public static int titleTextColor;
        public static int titleTextStyle;
        public static int toolbarNavigationButtonStyle;
        public static int toolbarStyle;
        public static int tooltipForegroundColor;
        public static int tooltipFrameBackground;
        public static int tooltipText;
        public static int track;
        public static int trackTint;
        public static int trackTintMode;
        public static int ttcIndex;
        public static int viewInflaterClass;
        public static int voiceIcon;
        public static int windowActionBar;
        public static int windowActionBarOverlay;
        public static int windowActionModeOverlay;
        public static int windowFixedHeightMajor;
        public static int windowFixedHeightMinor;
        public static int windowFixedWidthMajor;
        public static int windowFixedWidthMinor;
        public static int windowMinWidthMajor;
        public static int windowMinWidthMinor;
        public static int windowNoTitle;

        private attr() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$bool */
    public static final class bool {
        public static int abc_action_bar_embed_tabs;
        public static int abc_allow_stacked_button_bar;
        public static int abc_config_actionMenuItemAllCaps;

        private bool() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$color */
    public static final class color {
        public static int abc_background_cache_hint_selector_material_dark;
        public static int abc_background_cache_hint_selector_material_light;
        public static int abc_btn_colored_borderless_text_material;
        public static int abc_btn_colored_text_material;
        public static int abc_color_highlight_material;
        public static int abc_hint_foreground_material_dark;
        public static int abc_hint_foreground_material_light;
        public static int abc_input_method_navigation_guard;
        public static int abc_primary_text_disable_only_material_dark;
        public static int abc_primary_text_disable_only_material_light;
        public static int abc_primary_text_material_dark;
        public static int abc_primary_text_material_light;
        public static int abc_search_url_text;
        public static int abc_search_url_text_normal;
        public static int abc_search_url_text_pressed;
        public static int abc_search_url_text_selected;
        public static int abc_secondary_text_material_dark;
        public static int abc_secondary_text_material_light;
        public static int abc_tint_btn_checkable;
        public static int abc_tint_default;
        public static int abc_tint_edittext;
        public static int abc_tint_seek_thumb;
        public static int abc_tint_spinner;
        public static int abc_tint_switch_track;
        public static int accent_material_dark;
        public static int accent_material_light;
        public static int background_floating_material_dark;
        public static int background_floating_material_light;
        public static int background_material_dark;
        public static int background_material_light;
        public static int bright_foreground_disabled_material_dark;
        public static int bright_foreground_disabled_material_light;
        public static int bright_foreground_inverse_material_dark;
        public static int bright_foreground_inverse_material_light;
        public static int bright_foreground_material_dark;
        public static int bright_foreground_material_light;
        public static int button_material_dark;
        public static int button_material_light;
        public static int dim_foreground_disabled_material_dark;
        public static int dim_foreground_disabled_material_light;
        public static int dim_foreground_material_dark;
        public static int dim_foreground_material_light;
        public static int error_color_material_dark;
        public static int error_color_material_light;
        public static int foreground_material_dark;
        public static int foreground_material_light;
        public static int highlighted_text_material_dark;
        public static int highlighted_text_material_light;
        public static int material_blue_grey_800;
        public static int material_blue_grey_900;
        public static int material_blue_grey_950;
        public static int material_deep_teal_200;
        public static int material_deep_teal_500;
        public static int material_grey_100;
        public static int material_grey_300;
        public static int material_grey_50;
        public static int material_grey_600;
        public static int material_grey_800;
        public static int material_grey_850;
        public static int material_grey_900;
        public static int notification_action_color_filter;
        public static int notification_icon_bg_color;
        public static int primary_dark_material_dark;
        public static int primary_dark_material_light;
        public static int primary_material_dark;
        public static int primary_material_light;
        public static int primary_text_default_material_dark;
        public static int primary_text_default_material_light;
        public static int primary_text_disabled_material_dark;
        public static int primary_text_disabled_material_light;
        public static int ripple_material_dark;
        public static int ripple_material_light;
        public static int secondary_text_default_material_dark;
        public static int secondary_text_default_material_light;
        public static int secondary_text_disabled_material_dark;
        public static int secondary_text_disabled_material_light;
        public static int switch_thumb_disabled_material_dark;
        public static int switch_thumb_disabled_material_light;
        public static int switch_thumb_material_dark;
        public static int switch_thumb_material_light;
        public static int switch_thumb_normal_material_dark;
        public static int switch_thumb_normal_material_light;
        public static int tooltip_background_dark;
        public static int tooltip_background_light;

        private color() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$dimen */
    public static final class dimen {
        public static int abc_action_bar_content_inset_material;
        public static int abc_action_bar_content_inset_with_nav;
        public static int abc_action_bar_default_height_material;
        public static int abc_action_bar_default_padding_end_material;
        public static int abc_action_bar_default_padding_start_material;
        public static int abc_action_bar_elevation_material;
        public static int abc_action_bar_icon_vertical_padding_material;
        public static int abc_action_bar_overflow_padding_end_material;
        public static int abc_action_bar_overflow_padding_start_material;
        public static int abc_action_bar_stacked_max_height;
        public static int abc_action_bar_stacked_tab_max_width;
        public static int abc_action_bar_subtitle_bottom_margin_material;
        public static int abc_action_bar_subtitle_top_margin_material;
        public static int abc_action_button_min_height_material;
        public static int abc_action_button_min_width_material;
        public static int abc_action_button_min_width_overflow_material;
        public static int abc_alert_dialog_button_bar_height;
        public static int abc_alert_dialog_button_dimen;
        public static int abc_button_inset_horizontal_material;
        public static int abc_button_inset_vertical_material;
        public static int abc_button_padding_horizontal_material;
        public static int abc_button_padding_vertical_material;
        public static int abc_cascading_menus_min_smallest_width;
        public static int abc_config_prefDialogWidth;
        public static int abc_control_corner_material;
        public static int abc_control_inset_material;
        public static int abc_control_padding_material;
        public static int abc_dialog_corner_radius_material;
        public static int abc_dialog_fixed_height_major;
        public static int abc_dialog_fixed_height_minor;
        public static int abc_dialog_fixed_width_major;
        public static int abc_dialog_fixed_width_minor;
        public static int abc_dialog_list_padding_bottom_no_buttons;
        public static int abc_dialog_list_padding_top_no_title;
        public static int abc_dialog_min_width_major;
        public static int abc_dialog_min_width_minor;
        public static int abc_dialog_padding_material;
        public static int abc_dialog_padding_top_material;
        public static int abc_dialog_title_divider_material;
        public static int abc_disabled_alpha_material_dark;
        public static int abc_disabled_alpha_material_light;
        public static int abc_dropdownitem_icon_width;
        public static int abc_dropdownitem_text_padding_left;
        public static int abc_dropdownitem_text_padding_right;
        public static int abc_edit_text_inset_bottom_material;
        public static int abc_edit_text_inset_horizontal_material;
        public static int abc_edit_text_inset_top_material;
        public static int abc_floating_window_z;
        public static int abc_list_item_height_large_material;
        public static int abc_list_item_height_material;
        public static int abc_list_item_height_small_material;
        public static int abc_list_item_padding_horizontal_material;
        public static int abc_panel_menu_list_width;
        public static int abc_progress_bar_height_material;
        public static int abc_search_view_preferred_height;
        public static int abc_search_view_preferred_width;
        public static int abc_seekbar_track_background_height_material;
        public static int abc_seekbar_track_progress_height_material;
        public static int abc_select_dialog_padding_start_material;
        public static int abc_switch_padding;
        public static int abc_text_size_body_1_material;
        public static int abc_text_size_body_2_material;
        public static int abc_text_size_button_material;
        public static int abc_text_size_caption_material;
        public static int abc_text_size_display_1_material;
        public static int abc_text_size_display_2_material;
        public static int abc_text_size_display_3_material;
        public static int abc_text_size_display_4_material;
        public static int abc_text_size_headline_material;
        public static int abc_text_size_large_material;
        public static int abc_text_size_medium_material;
        public static int abc_text_size_menu_header_material;
        public static int abc_text_size_menu_material;
        public static int abc_text_size_small_material;
        public static int abc_text_size_subhead_material;
        public static int abc_text_size_subtitle_material_toolbar;
        public static int abc_text_size_title_material;
        public static int abc_text_size_title_material_toolbar;
        public static int compat_button_inset_horizontal_material;
        public static int compat_button_inset_vertical_material;
        public static int compat_button_padding_horizontal_material;
        public static int compat_button_padding_vertical_material;
        public static int compat_control_corner_material;
        public static int compat_notification_large_icon_max_height;
        public static int compat_notification_large_icon_max_width;
        public static int disabled_alpha_material_dark;
        public static int disabled_alpha_material_light;
        public static int highlight_alpha_material_colored;
        public static int highlight_alpha_material_dark;
        public static int highlight_alpha_material_light;
        public static int hint_alpha_material_dark;
        public static int hint_alpha_material_light;
        public static int hint_pressed_alpha_material_dark;
        public static int hint_pressed_alpha_material_light;
        public static int notification_action_icon_size;
        public static int notification_action_text_size;
        public static int notification_big_circle_margin;
        public static int notification_content_margin_start;
        public static int notification_large_icon_height;
        public static int notification_large_icon_width;
        public static int notification_main_column_padding_top;
        public static int notification_media_narrow_margin;
        public static int notification_right_icon_size;
        public static int notification_right_side_padding_top;
        public static int notification_small_icon_background_padding;
        public static int notification_small_icon_size_as_large;
        public static int notification_subtext_size;
        public static int notification_top_pad;
        public static int notification_top_pad_large_text;
        public static int tooltip_corner_radius;
        public static int tooltip_horizontal_padding;
        public static int tooltip_margin;
        public static int tooltip_precise_anchor_extra_offset;
        public static int tooltip_precise_anchor_threshold;
        public static int tooltip_vertical_padding;
        public static int tooltip_y_offset_non_touch;
        public static int tooltip_y_offset_touch;

        private dimen() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$drawable */
    public static final class drawable {
        public static int abc_ab_share_pack_mtrl_alpha;
        public static int abc_action_bar_item_background_material;
        public static int abc_btn_borderless_material;
        public static int abc_btn_check_material;
        public static int abc_btn_check_material_anim;
        public static int abc_btn_check_to_on_mtrl_000;
        public static int abc_btn_check_to_on_mtrl_015;
        public static int abc_btn_colored_material;
        public static int abc_btn_default_mtrl_shape;
        public static int abc_btn_radio_material;
        public static int abc_btn_radio_material_anim;
        public static int abc_btn_radio_to_on_mtrl_000;
        public static int abc_btn_radio_to_on_mtrl_015;
        public static int abc_btn_switch_to_on_mtrl_00001;
        public static int abc_btn_switch_to_on_mtrl_00012;
        public static int abc_cab_background_internal_bg;
        public static int abc_cab_background_top_material;
        public static int abc_cab_background_top_mtrl_alpha;
        public static int abc_control_background_material;
        public static int abc_dialog_material_background;
        public static int abc_edit_text_material;
        public static int abc_ic_ab_back_material;
        public static int abc_ic_arrow_drop_right_black_24dp;
        public static int abc_ic_clear_material;
        public static int abc_ic_commit_search_api_mtrl_alpha;
        public static int abc_ic_go_search_api_material;
        public static int abc_ic_menu_copy_mtrl_am_alpha;
        public static int abc_ic_menu_cut_mtrl_alpha;
        public static int abc_ic_menu_overflow_material;
        public static int abc_ic_menu_paste_mtrl_am_alpha;
        public static int abc_ic_menu_selectall_mtrl_alpha;
        public static int abc_ic_menu_share_mtrl_alpha;
        public static int abc_ic_search_api_material;
        public static int abc_ic_star_black_16dp;
        public static int abc_ic_star_black_36dp;
        public static int abc_ic_star_black_48dp;
        public static int abc_ic_star_half_black_16dp;
        public static int abc_ic_star_half_black_36dp;
        public static int abc_ic_star_half_black_48dp;
        public static int abc_ic_voice_search_api_material;
        public static int abc_item_background_holo_dark;
        public static int abc_item_background_holo_light;
        public static int abc_list_divider_material;
        public static int abc_list_divider_mtrl_alpha;
        public static int abc_list_focused_holo;
        public static int abc_list_longpressed_holo;
        public static int abc_list_pressed_holo_dark;
        public static int abc_list_pressed_holo_light;
        public static int abc_list_selector_background_transition_holo_dark;
        public static int abc_list_selector_background_transition_holo_light;
        public static int abc_list_selector_disabled_holo_dark;
        public static int abc_list_selector_disabled_holo_light;
        public static int abc_list_selector_holo_dark;
        public static int abc_list_selector_holo_light;
        public static int abc_menu_hardkey_panel_mtrl_mult;
        public static int abc_popup_background_mtrl_mult;
        public static int abc_ratingbar_indicator_material;
        public static int abc_ratingbar_material;
        public static int abc_ratingbar_small_material;
        public static int abc_scrubber_control_off_mtrl_alpha;
        public static int abc_scrubber_control_to_pressed_mtrl_000;
        public static int abc_scrubber_control_to_pressed_mtrl_005;
        public static int abc_scrubber_primary_mtrl_alpha;
        public static int abc_scrubber_track_mtrl_alpha;
        public static int abc_seekbar_thumb_material;
        public static int abc_seekbar_tick_mark_material;
        public static int abc_seekbar_track_material;
        public static int abc_spinner_mtrl_am_alpha;
        public static int abc_spinner_textfield_background_material;
        public static int abc_switch_thumb_material;
        public static int abc_switch_track_mtrl_alpha;
        public static int abc_tab_indicator_material;
        public static int abc_tab_indicator_mtrl_alpha;
        public static int abc_text_cursor_material;
        public static int abc_text_select_handle_left_mtrl_dark;
        public static int abc_text_select_handle_left_mtrl_light;
        public static int abc_text_select_handle_middle_mtrl_dark;
        public static int abc_text_select_handle_middle_mtrl_light;
        public static int abc_text_select_handle_right_mtrl_dark;
        public static int abc_text_select_handle_right_mtrl_light;
        public static int abc_textfield_activated_mtrl_alpha;
        public static int abc_textfield_default_mtrl_alpha;
        public static int abc_textfield_search_activated_mtrl_alpha;
        public static int abc_textfield_search_default_mtrl_alpha;
        public static int abc_textfield_search_material;
        public static int abc_vector_test;
        public static int btn_checkbox_checked_mtrl;
        public static int btn_checkbox_checked_to_unchecked_mtrl_animation;
        public static int btn_checkbox_unchecked_mtrl;
        public static int btn_checkbox_unchecked_to_checked_mtrl_animation;
        public static int btn_radio_off_mtrl;
        public static int btn_radio_off_to_on_mtrl_animation;
        public static int btn_radio_on_mtrl;
        public static int btn_radio_on_to_off_mtrl_animation;
        public static int notification_action_background;
        public static int notification_bg;
        public static int notification_bg_low;
        public static int notification_bg_low_normal;
        public static int notification_bg_low_pressed;
        public static int notification_bg_normal;
        public static int notification_bg_normal_pressed;
        public static int notification_icon_background;
        public static int notification_template_icon_bg;
        public static int notification_template_icon_low_bg;
        public static int notification_tile_bg;
        public static int notify_panel_notification_icon_bg;
        public static int tooltip_frame_dark;
        public static int tooltip_frame_light;

        private drawable() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$id */
    public static final class C5914id {
        public static int accessibility_action_clickable_span;
        public static int accessibility_custom_action_0;
        public static int accessibility_custom_action_1;
        public static int accessibility_custom_action_10;
        public static int accessibility_custom_action_11;
        public static int accessibility_custom_action_12;
        public static int accessibility_custom_action_13;
        public static int accessibility_custom_action_14;
        public static int accessibility_custom_action_15;
        public static int accessibility_custom_action_16;
        public static int accessibility_custom_action_17;
        public static int accessibility_custom_action_18;
        public static int accessibility_custom_action_19;
        public static int accessibility_custom_action_2;
        public static int accessibility_custom_action_20;
        public static int accessibility_custom_action_21;
        public static int accessibility_custom_action_22;
        public static int accessibility_custom_action_23;
        public static int accessibility_custom_action_24;
        public static int accessibility_custom_action_25;
        public static int accessibility_custom_action_26;
        public static int accessibility_custom_action_27;
        public static int accessibility_custom_action_28;
        public static int accessibility_custom_action_29;
        public static int accessibility_custom_action_3;
        public static int accessibility_custom_action_30;
        public static int accessibility_custom_action_31;
        public static int accessibility_custom_action_4;
        public static int accessibility_custom_action_5;
        public static int accessibility_custom_action_6;
        public static int accessibility_custom_action_7;
        public static int accessibility_custom_action_8;
        public static int accessibility_custom_action_9;
        public static int action_bar;
        public static int action_bar_activity_content;
        public static int action_bar_container;
        public static int action_bar_root;
        public static int action_bar_spinner;
        public static int action_bar_subtitle;
        public static int action_bar_title;
        public static int action_container;
        public static int action_context_bar;
        public static int action_divider;
        public static int action_image;
        public static int action_menu_divider;
        public static int action_menu_presenter;
        public static int action_mode_bar;
        public static int action_mode_bar_stub;
        public static int action_mode_close_button;
        public static int action_text;
        public static int actions;
        public static int activity_chooser_view_content;
        public static int add;
        public static int alertTitle;
        public static int async;
        public static int blocking;
        public static int buttonPanel;
        public static int checkbox;
        public static int checked;
        public static int chronometer;
        public static int content;
        public static int contentPanel;
        public static int custom;
        public static int customPanel;
        public static int decor_content_parent;
        public static int default_activity_button;
        public static int dialog_button;
        public static int edit_query;
        public static int expand_activities_button;
        public static int expanded_menu;
        public static int forever;
        public static int group_divider;
        public static int home;
        public static int icon;
        public static int icon_group;
        public static int image;
        public static int info;
        public static int italic;
        public static int line1;
        public static int line3;
        public static int listMode;
        public static int list_item;
        public static int message;
        public static int multiply;
        public static int none;
        public static int normal;
        public static int notification_background;
        public static int notification_main_column;
        public static int notification_main_column_container;
        public static int off;

        /* renamed from: on */
        public static int f8612on;
        public static int parentPanel;
        public static int progress_circular;
        public static int progress_horizontal;
        public static int radio;
        public static int right_icon;
        public static int right_side;
        public static int screen;
        public static int scrollIndicatorDown;
        public static int scrollIndicatorUp;
        public static int scrollView;
        public static int search_badge;
        public static int search_bar;
        public static int search_button;
        public static int search_close_btn;
        public static int search_edit_frame;
        public static int search_go_btn;
        public static int search_mag_icon;
        public static int search_plate;
        public static int search_src_text;
        public static int search_voice_btn;
        public static int select_dialog_listview;
        public static int shortcut;
        public static int spacer;
        public static int split_action_bar;
        public static int src_atop;
        public static int src_in;
        public static int src_over;
        public static int submenuarrow;
        public static int submit_area;
        public static int tabMode;
        public static int tag_accessibility_actions;
        public static int tag_accessibility_clickable_spans;
        public static int tag_accessibility_heading;
        public static int tag_accessibility_pane_title;
        public static int tag_screen_reader_focusable;
        public static int tag_transition_group;
        public static int tag_unhandled_key_event_manager;
        public static int tag_unhandled_key_listeners;
        public static int text;
        public static int text2;
        public static int textSpacerNoButtons;
        public static int textSpacerNoTitle;
        public static int time;
        public static int title;
        public static int titleDividerNoCustom;
        public static int title_template;
        public static int topPanel;
        public static int unchecked;
        public static int uniform;

        /* renamed from: up */
        public static int f8613up;
        public static int wrap_content;

        private C5914id() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$integer */
    public static final class integer {
        public static int abc_config_activityDefaultDur;
        public static int abc_config_activityShortDur;
        public static int cancel_button_image_alpha;
        public static int config_tooltipAnimTime;
        public static int status_bar_notification_info_maxnum;

        private integer() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$interpolator */
    public static final class interpolator {
        public static int btn_checkbox_checked_mtrl_animation_interpolator_0;
        public static int btn_checkbox_checked_mtrl_animation_interpolator_1;
        public static int btn_checkbox_unchecked_mtrl_animation_interpolator_0;
        public static int btn_checkbox_unchecked_mtrl_animation_interpolator_1;
        public static int btn_radio_to_off_mtrl_animation_interpolator_0;
        public static int btn_radio_to_on_mtrl_animation_interpolator_0;
        public static int fast_out_slow_in;

        private interpolator() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$layout */
    public static final class layout {
        public static int abc_action_bar_title_item;
        public static int abc_action_bar_up_container;
        public static int abc_action_menu_item_layout;
        public static int abc_action_menu_layout;
        public static int abc_action_mode_bar;
        public static int abc_action_mode_close_item_material;
        public static int abc_activity_chooser_view;
        public static int abc_activity_chooser_view_list_item;
        public static int abc_alert_dialog_button_bar_material;
        public static int abc_alert_dialog_material;
        public static int abc_alert_dialog_title_material;
        public static int abc_cascading_menu_item_layout;
        public static int abc_dialog_title_material;
        public static int abc_expanded_menu_layout;
        public static int abc_list_menu_item_checkbox;
        public static int abc_list_menu_item_icon;
        public static int abc_list_menu_item_layout;
        public static int abc_list_menu_item_radio;
        public static int abc_popup_menu_header_item_layout;
        public static int abc_popup_menu_item_layout;
        public static int abc_screen_content_include;
        public static int abc_screen_simple;
        public static int abc_screen_simple_overlay_action_mode;
        public static int abc_screen_toolbar;
        public static int abc_search_dropdown_item_icons_2line;
        public static int abc_search_view;
        public static int abc_select_dialog_material;
        public static int abc_tooltip;
        public static int custom_dialog;
        public static int notification_action;
        public static int notification_action_tombstone;
        public static int notification_template_custom_big;
        public static int notification_template_icon_group;
        public static int notification_template_part_chronometer;
        public static int notification_template_part_time;
        public static int select_dialog_item_material;
        public static int select_dialog_multichoice_material;
        public static int select_dialog_singlechoice_material;
        public static int support_simple_spinner_dropdown_item;

        private layout() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$string */
    public static final class string {
        public static int abc_action_bar_home_description;
        public static int abc_action_bar_up_description;
        public static int abc_action_menu_overflow_description;
        public static int abc_action_mode_done;
        public static int abc_activity_chooser_view_see_all;
        public static int abc_activitychooserview_choose_application;
        public static int abc_capital_off;
        public static int abc_capital_on;
        public static int abc_menu_alt_shortcut_label;
        public static int abc_menu_ctrl_shortcut_label;
        public static int abc_menu_delete_shortcut_label;
        public static int abc_menu_enter_shortcut_label;
        public static int abc_menu_function_shortcut_label;
        public static int abc_menu_meta_shortcut_label;
        public static int abc_menu_shift_shortcut_label;
        public static int abc_menu_space_shortcut_label;
        public static int abc_menu_sym_shortcut_label;
        public static int abc_prepend_shortcut_label;
        public static int abc_search_hint;
        public static int abc_searchview_description_clear;
        public static int abc_searchview_description_query;
        public static int abc_searchview_description_search;
        public static int abc_searchview_description_submit;
        public static int abc_searchview_description_voice;
        public static int abc_shareactionprovider_share_with;
        public static int abc_shareactionprovider_share_with_application;
        public static int abc_toolbar_collapse_description;
        public static int search_menu_title;
        public static int status_bar_notification_info_overflow;

        private string() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$style */
    public static final class style {
        public static int AlertDialog_AppCompat;
        public static int AlertDialog_AppCompat_Light;
        public static int Animation_AppCompat_Dialog;
        public static int Animation_AppCompat_DropDownUp;
        public static int Animation_AppCompat_Tooltip;
        public static int Base_AlertDialog_AppCompat;
        public static int Base_AlertDialog_AppCompat_Light;
        public static int Base_Animation_AppCompat_Dialog;
        public static int Base_Animation_AppCompat_DropDownUp;
        public static int Base_Animation_AppCompat_Tooltip;
        public static int Base_DialogWindowTitleBackground_AppCompat;
        public static int Base_DialogWindowTitle_AppCompat;
        public static int Base_TextAppearance_AppCompat;
        public static int Base_TextAppearance_AppCompat_Body1;
        public static int Base_TextAppearance_AppCompat_Body2;
        public static int Base_TextAppearance_AppCompat_Button;
        public static int Base_TextAppearance_AppCompat_Caption;
        public static int Base_TextAppearance_AppCompat_Display1;
        public static int Base_TextAppearance_AppCompat_Display2;
        public static int Base_TextAppearance_AppCompat_Display3;
        public static int Base_TextAppearance_AppCompat_Display4;
        public static int Base_TextAppearance_AppCompat_Headline;
        public static int Base_TextAppearance_AppCompat_Inverse;
        public static int Base_TextAppearance_AppCompat_Large;
        public static int Base_TextAppearance_AppCompat_Large_Inverse;
        public static int Base_TextAppearance_AppCompat_Light_Widget_PopupMenu_Large;
        public static int Base_TextAppearance_AppCompat_Light_Widget_PopupMenu_Small;
        public static int Base_TextAppearance_AppCompat_Medium;
        public static int Base_TextAppearance_AppCompat_Medium_Inverse;
        public static int Base_TextAppearance_AppCompat_Menu;
        public static int Base_TextAppearance_AppCompat_SearchResult;
        public static int Base_TextAppearance_AppCompat_SearchResult_Subtitle;
        public static int Base_TextAppearance_AppCompat_SearchResult_Title;
        public static int Base_TextAppearance_AppCompat_Small;
        public static int Base_TextAppearance_AppCompat_Small_Inverse;
        public static int Base_TextAppearance_AppCompat_Subhead;
        public static int Base_TextAppearance_AppCompat_Subhead_Inverse;
        public static int Base_TextAppearance_AppCompat_Title;
        public static int Base_TextAppearance_AppCompat_Title_Inverse;
        public static int Base_TextAppearance_AppCompat_Tooltip;
        public static int Base_TextAppearance_AppCompat_Widget_ActionBar_Menu;
        public static int Base_TextAppearance_AppCompat_Widget_ActionBar_Subtitle;
        public static int Base_TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse;
        public static int Base_TextAppearance_AppCompat_Widget_ActionBar_Title;
        public static int Base_TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse;
        public static int Base_TextAppearance_AppCompat_Widget_ActionMode_Subtitle;
        public static int Base_TextAppearance_AppCompat_Widget_ActionMode_Title;
        public static int Base_TextAppearance_AppCompat_Widget_Button;
        public static int Base_TextAppearance_AppCompat_Widget_Button_Borderless_Colored;
        public static int Base_TextAppearance_AppCompat_Widget_Button_Colored;
        public static int Base_TextAppearance_AppCompat_Widget_Button_Inverse;
        public static int Base_TextAppearance_AppCompat_Widget_DropDownItem;
        public static int Base_TextAppearance_AppCompat_Widget_PopupMenu_Header;
        public static int Base_TextAppearance_AppCompat_Widget_PopupMenu_Large;
        public static int Base_TextAppearance_AppCompat_Widget_PopupMenu_Small;
        public static int Base_TextAppearance_AppCompat_Widget_Switch;
        public static int Base_TextAppearance_AppCompat_Widget_TextView_SpinnerItem;
        public static int Base_TextAppearance_Widget_AppCompat_ExpandedMenu_Item;
        public static int Base_TextAppearance_Widget_AppCompat_Toolbar_Subtitle;
        public static int Base_TextAppearance_Widget_AppCompat_Toolbar_Title;
        public static int Base_ThemeOverlay_AppCompat;
        public static int Base_ThemeOverlay_AppCompat_ActionBar;
        public static int Base_ThemeOverlay_AppCompat_Dark;
        public static int Base_ThemeOverlay_AppCompat_Dark_ActionBar;
        public static int Base_ThemeOverlay_AppCompat_Dialog;
        public static int Base_ThemeOverlay_AppCompat_Dialog_Alert;
        public static int Base_ThemeOverlay_AppCompat_Light;
        public static int Base_Theme_AppCompat;
        public static int Base_Theme_AppCompat_CompactMenu;
        public static int Base_Theme_AppCompat_Dialog;
        public static int Base_Theme_AppCompat_DialogWhenLarge;
        public static int Base_Theme_AppCompat_Dialog_Alert;
        public static int Base_Theme_AppCompat_Dialog_FixedSize;
        public static int Base_Theme_AppCompat_Dialog_MinWidth;
        public static int Base_Theme_AppCompat_Light;
        public static int Base_Theme_AppCompat_Light_DarkActionBar;
        public static int Base_Theme_AppCompat_Light_Dialog;
        public static int Base_Theme_AppCompat_Light_DialogWhenLarge;
        public static int Base_Theme_AppCompat_Light_Dialog_Alert;
        public static int Base_Theme_AppCompat_Light_Dialog_FixedSize;
        public static int Base_Theme_AppCompat_Light_Dialog_MinWidth;
        public static int Base_V21_ThemeOverlay_AppCompat_Dialog;
        public static int Base_V21_Theme_AppCompat;
        public static int Base_V21_Theme_AppCompat_Dialog;
        public static int Base_V21_Theme_AppCompat_Light;
        public static int Base_V21_Theme_AppCompat_Light_Dialog;
        public static int Base_V22_Theme_AppCompat;
        public static int Base_V22_Theme_AppCompat_Light;
        public static int Base_V23_Theme_AppCompat;
        public static int Base_V23_Theme_AppCompat_Light;
        public static int Base_V26_Theme_AppCompat;
        public static int Base_V26_Theme_AppCompat_Light;
        public static int Base_V26_Widget_AppCompat_Toolbar;
        public static int Base_V28_Theme_AppCompat;
        public static int Base_V28_Theme_AppCompat_Light;
        public static int Base_V7_ThemeOverlay_AppCompat_Dialog;
        public static int Base_V7_Theme_AppCompat;
        public static int Base_V7_Theme_AppCompat_Dialog;
        public static int Base_V7_Theme_AppCompat_Light;
        public static int Base_V7_Theme_AppCompat_Light_Dialog;
        public static int Base_V7_Widget_AppCompat_AutoCompleteTextView;
        public static int Base_V7_Widget_AppCompat_EditText;
        public static int Base_V7_Widget_AppCompat_Toolbar;
        public static int Base_Widget_AppCompat_ActionBar;
        public static int Base_Widget_AppCompat_ActionBar_Solid;
        public static int Base_Widget_AppCompat_ActionBar_TabBar;
        public static int Base_Widget_AppCompat_ActionBar_TabText;
        public static int Base_Widget_AppCompat_ActionBar_TabView;
        public static int Base_Widget_AppCompat_ActionButton;
        public static int Base_Widget_AppCompat_ActionButton_CloseMode;
        public static int Base_Widget_AppCompat_ActionButton_Overflow;
        public static int Base_Widget_AppCompat_ActionMode;
        public static int Base_Widget_AppCompat_ActivityChooserView;
        public static int Base_Widget_AppCompat_AutoCompleteTextView;
        public static int Base_Widget_AppCompat_Button;
        public static int Base_Widget_AppCompat_ButtonBar;
        public static int Base_Widget_AppCompat_ButtonBar_AlertDialog;
        public static int Base_Widget_AppCompat_Button_Borderless;
        public static int Base_Widget_AppCompat_Button_Borderless_Colored;
        public static int Base_Widget_AppCompat_Button_ButtonBar_AlertDialog;
        public static int Base_Widget_AppCompat_Button_Colored;
        public static int Base_Widget_AppCompat_Button_Small;
        public static int Base_Widget_AppCompat_CompoundButton_CheckBox;
        public static int Base_Widget_AppCompat_CompoundButton_RadioButton;
        public static int Base_Widget_AppCompat_CompoundButton_Switch;
        public static int Base_Widget_AppCompat_DrawerArrowToggle;
        public static int Base_Widget_AppCompat_DrawerArrowToggle_Common;
        public static int Base_Widget_AppCompat_DropDownItem_Spinner;
        public static int Base_Widget_AppCompat_EditText;
        public static int Base_Widget_AppCompat_ImageButton;
        public static int Base_Widget_AppCompat_Light_ActionBar;
        public static int Base_Widget_AppCompat_Light_ActionBar_Solid;
        public static int Base_Widget_AppCompat_Light_ActionBar_TabBar;
        public static int Base_Widget_AppCompat_Light_ActionBar_TabText;
        public static int Base_Widget_AppCompat_Light_ActionBar_TabText_Inverse;
        public static int Base_Widget_AppCompat_Light_ActionBar_TabView;
        public static int Base_Widget_AppCompat_Light_PopupMenu;
        public static int Base_Widget_AppCompat_Light_PopupMenu_Overflow;
        public static int Base_Widget_AppCompat_ListMenuView;
        public static int Base_Widget_AppCompat_ListPopupWindow;
        public static int Base_Widget_AppCompat_ListView;
        public static int Base_Widget_AppCompat_ListView_DropDown;
        public static int Base_Widget_AppCompat_ListView_Menu;
        public static int Base_Widget_AppCompat_PopupMenu;
        public static int Base_Widget_AppCompat_PopupMenu_Overflow;
        public static int Base_Widget_AppCompat_PopupWindow;
        public static int Base_Widget_AppCompat_ProgressBar;
        public static int Base_Widget_AppCompat_ProgressBar_Horizontal;
        public static int Base_Widget_AppCompat_RatingBar;
        public static int Base_Widget_AppCompat_RatingBar_Indicator;
        public static int Base_Widget_AppCompat_RatingBar_Small;
        public static int Base_Widget_AppCompat_SearchView;
        public static int Base_Widget_AppCompat_SearchView_ActionBar;
        public static int Base_Widget_AppCompat_SeekBar;
        public static int Base_Widget_AppCompat_SeekBar_Discrete;
        public static int Base_Widget_AppCompat_Spinner;
        public static int Base_Widget_AppCompat_Spinner_Underlined;
        public static int Base_Widget_AppCompat_TextView;
        public static int Base_Widget_AppCompat_TextView_SpinnerItem;
        public static int Base_Widget_AppCompat_Toolbar;
        public static int Base_Widget_AppCompat_Toolbar_Button_Navigation;
        public static int Platform_AppCompat;
        public static int Platform_AppCompat_Light;
        public static int Platform_ThemeOverlay_AppCompat;
        public static int Platform_ThemeOverlay_AppCompat_Dark;
        public static int Platform_ThemeOverlay_AppCompat_Light;
        public static int Platform_V21_AppCompat;
        public static int Platform_V21_AppCompat_Light;
        public static int Platform_V25_AppCompat;
        public static int Platform_V25_AppCompat_Light;
        public static int Platform_Widget_AppCompat_Spinner;
        public static int RtlOverlay_DialogWindowTitle_AppCompat;
        public static int RtlOverlay_Widget_AppCompat_ActionBar_TitleItem;
        public static int RtlOverlay_Widget_AppCompat_DialogTitle_Icon;
        public static int RtlOverlay_Widget_AppCompat_PopupMenuItem;
        public static int RtlOverlay_Widget_AppCompat_PopupMenuItem_InternalGroup;
        public static int RtlOverlay_Widget_AppCompat_PopupMenuItem_Shortcut;
        public static int RtlOverlay_Widget_AppCompat_PopupMenuItem_SubmenuArrow;
        public static int RtlOverlay_Widget_AppCompat_PopupMenuItem_Text;
        public static int RtlOverlay_Widget_AppCompat_PopupMenuItem_Title;
        public static int RtlOverlay_Widget_AppCompat_SearchView_MagIcon;
        public static int RtlOverlay_Widget_AppCompat_Search_DropDown;
        public static int RtlOverlay_Widget_AppCompat_Search_DropDown_Icon1;
        public static int RtlOverlay_Widget_AppCompat_Search_DropDown_Icon2;
        public static int RtlOverlay_Widget_AppCompat_Search_DropDown_Query;
        public static int RtlOverlay_Widget_AppCompat_Search_DropDown_Text;
        public static int RtlUnderlay_Widget_AppCompat_ActionButton;
        public static int RtlUnderlay_Widget_AppCompat_ActionButton_Overflow;
        public static int TextAppearance_AppCompat;
        public static int TextAppearance_AppCompat_Body1;
        public static int TextAppearance_AppCompat_Body2;
        public static int TextAppearance_AppCompat_Button;
        public static int TextAppearance_AppCompat_Caption;
        public static int TextAppearance_AppCompat_Display1;
        public static int TextAppearance_AppCompat_Display2;
        public static int TextAppearance_AppCompat_Display3;
        public static int TextAppearance_AppCompat_Display4;
        public static int TextAppearance_AppCompat_Headline;
        public static int TextAppearance_AppCompat_Inverse;
        public static int TextAppearance_AppCompat_Large;
        public static int TextAppearance_AppCompat_Large_Inverse;
        public static int TextAppearance_AppCompat_Light_SearchResult_Subtitle;
        public static int TextAppearance_AppCompat_Light_SearchResult_Title;
        public static int TextAppearance_AppCompat_Light_Widget_PopupMenu_Large;
        public static int TextAppearance_AppCompat_Light_Widget_PopupMenu_Small;
        public static int TextAppearance_AppCompat_Medium;
        public static int TextAppearance_AppCompat_Medium_Inverse;
        public static int TextAppearance_AppCompat_Menu;
        public static int TextAppearance_AppCompat_SearchResult_Subtitle;
        public static int TextAppearance_AppCompat_SearchResult_Title;
        public static int TextAppearance_AppCompat_Small;
        public static int TextAppearance_AppCompat_Small_Inverse;
        public static int TextAppearance_AppCompat_Subhead;
        public static int TextAppearance_AppCompat_Subhead_Inverse;
        public static int TextAppearance_AppCompat_Title;
        public static int TextAppearance_AppCompat_Title_Inverse;
        public static int TextAppearance_AppCompat_Tooltip;
        public static int TextAppearance_AppCompat_Widget_ActionBar_Menu;
        public static int TextAppearance_AppCompat_Widget_ActionBar_Subtitle;
        public static int TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse;
        public static int TextAppearance_AppCompat_Widget_ActionBar_Title;
        public static int TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse;
        public static int TextAppearance_AppCompat_Widget_ActionMode_Subtitle;
        public static int TextAppearance_AppCompat_Widget_ActionMode_Subtitle_Inverse;
        public static int TextAppearance_AppCompat_Widget_ActionMode_Title;
        public static int TextAppearance_AppCompat_Widget_ActionMode_Title_Inverse;
        public static int TextAppearance_AppCompat_Widget_Button;
        public static int TextAppearance_AppCompat_Widget_Button_Borderless_Colored;
        public static int TextAppearance_AppCompat_Widget_Button_Colored;
        public static int TextAppearance_AppCompat_Widget_Button_Inverse;
        public static int TextAppearance_AppCompat_Widget_DropDownItem;
        public static int TextAppearance_AppCompat_Widget_PopupMenu_Header;
        public static int TextAppearance_AppCompat_Widget_PopupMenu_Large;
        public static int TextAppearance_AppCompat_Widget_PopupMenu_Small;
        public static int TextAppearance_AppCompat_Widget_Switch;
        public static int TextAppearance_AppCompat_Widget_TextView_SpinnerItem;
        public static int TextAppearance_Compat_Notification;
        public static int TextAppearance_Compat_Notification_Info;
        public static int TextAppearance_Compat_Notification_Line2;
        public static int TextAppearance_Compat_Notification_Time;
        public static int TextAppearance_Compat_Notification_Title;
        public static int TextAppearance_Widget_AppCompat_ExpandedMenu_Item;
        public static int TextAppearance_Widget_AppCompat_Toolbar_Subtitle;
        public static int TextAppearance_Widget_AppCompat_Toolbar_Title;
        public static int ThemeOverlay_AppCompat;
        public static int ThemeOverlay_AppCompat_ActionBar;
        public static int ThemeOverlay_AppCompat_Dark;
        public static int ThemeOverlay_AppCompat_Dark_ActionBar;
        public static int ThemeOverlay_AppCompat_DayNight;
        public static int ThemeOverlay_AppCompat_DayNight_ActionBar;
        public static int ThemeOverlay_AppCompat_Dialog;
        public static int ThemeOverlay_AppCompat_Dialog_Alert;
        public static int ThemeOverlay_AppCompat_Light;
        public static int Theme_AppCompat;
        public static int Theme_AppCompat_CompactMenu;
        public static int Theme_AppCompat_DayNight;
        public static int Theme_AppCompat_DayNight_DarkActionBar;
        public static int Theme_AppCompat_DayNight_Dialog;
        public static int Theme_AppCompat_DayNight_DialogWhenLarge;
        public static int Theme_AppCompat_DayNight_Dialog_Alert;
        public static int Theme_AppCompat_DayNight_Dialog_MinWidth;
        public static int Theme_AppCompat_DayNight_NoActionBar;
        public static int Theme_AppCompat_Dialog;
        public static int Theme_AppCompat_DialogWhenLarge;
        public static int Theme_AppCompat_Dialog_Alert;
        public static int Theme_AppCompat_Dialog_MinWidth;
        public static int Theme_AppCompat_Light;
        public static int Theme_AppCompat_Light_DarkActionBar;
        public static int Theme_AppCompat_Light_Dialog;
        public static int Theme_AppCompat_Light_DialogWhenLarge;
        public static int Theme_AppCompat_Light_Dialog_Alert;
        public static int Theme_AppCompat_Light_Dialog_MinWidth;
        public static int Theme_AppCompat_Light_NoActionBar;
        public static int Theme_AppCompat_NoActionBar;
        public static int Widget_AppCompat_ActionBar;
        public static int Widget_AppCompat_ActionBar_Solid;
        public static int Widget_AppCompat_ActionBar_TabBar;
        public static int Widget_AppCompat_ActionBar_TabText;
        public static int Widget_AppCompat_ActionBar_TabView;
        public static int Widget_AppCompat_ActionButton;
        public static int Widget_AppCompat_ActionButton_CloseMode;
        public static int Widget_AppCompat_ActionButton_Overflow;
        public static int Widget_AppCompat_ActionMode;
        public static int Widget_AppCompat_ActivityChooserView;
        public static int Widget_AppCompat_AutoCompleteTextView;
        public static int Widget_AppCompat_Button;
        public static int Widget_AppCompat_ButtonBar;
        public static int Widget_AppCompat_ButtonBar_AlertDialog;
        public static int Widget_AppCompat_Button_Borderless;
        public static int Widget_AppCompat_Button_Borderless_Colored;
        public static int Widget_AppCompat_Button_ButtonBar_AlertDialog;
        public static int Widget_AppCompat_Button_Colored;
        public static int Widget_AppCompat_Button_Small;
        public static int Widget_AppCompat_CompoundButton_CheckBox;
        public static int Widget_AppCompat_CompoundButton_RadioButton;
        public static int Widget_AppCompat_CompoundButton_Switch;
        public static int Widget_AppCompat_DrawerArrowToggle;
        public static int Widget_AppCompat_DropDownItem_Spinner;
        public static int Widget_AppCompat_EditText;
        public static int Widget_AppCompat_ImageButton;
        public static int Widget_AppCompat_Light_ActionBar;
        public static int Widget_AppCompat_Light_ActionBar_Solid;
        public static int Widget_AppCompat_Light_ActionBar_Solid_Inverse;
        public static int Widget_AppCompat_Light_ActionBar_TabBar;
        public static int Widget_AppCompat_Light_ActionBar_TabBar_Inverse;
        public static int Widget_AppCompat_Light_ActionBar_TabText;
        public static int Widget_AppCompat_Light_ActionBar_TabText_Inverse;
        public static int Widget_AppCompat_Light_ActionBar_TabView;
        public static int Widget_AppCompat_Light_ActionBar_TabView_Inverse;
        public static int Widget_AppCompat_Light_ActionButton;
        public static int Widget_AppCompat_Light_ActionButton_CloseMode;
        public static int Widget_AppCompat_Light_ActionButton_Overflow;
        public static int Widget_AppCompat_Light_ActionMode_Inverse;
        public static int Widget_AppCompat_Light_ActivityChooserView;
        public static int Widget_AppCompat_Light_AutoCompleteTextView;
        public static int Widget_AppCompat_Light_DropDownItem_Spinner;
        public static int Widget_AppCompat_Light_ListPopupWindow;
        public static int Widget_AppCompat_Light_ListView_DropDown;
        public static int Widget_AppCompat_Light_PopupMenu;
        public static int Widget_AppCompat_Light_PopupMenu_Overflow;
        public static int Widget_AppCompat_Light_SearchView;
        public static int Widget_AppCompat_Light_Spinner_DropDown_ActionBar;
        public static int Widget_AppCompat_ListMenuView;
        public static int Widget_AppCompat_ListPopupWindow;
        public static int Widget_AppCompat_ListView;
        public static int Widget_AppCompat_ListView_DropDown;
        public static int Widget_AppCompat_ListView_Menu;
        public static int Widget_AppCompat_PopupMenu;
        public static int Widget_AppCompat_PopupMenu_Overflow;
        public static int Widget_AppCompat_PopupWindow;
        public static int Widget_AppCompat_ProgressBar;
        public static int Widget_AppCompat_ProgressBar_Horizontal;
        public static int Widget_AppCompat_RatingBar;
        public static int Widget_AppCompat_RatingBar_Indicator;
        public static int Widget_AppCompat_RatingBar_Small;
        public static int Widget_AppCompat_SearchView;
        public static int Widget_AppCompat_SearchView_ActionBar;
        public static int Widget_AppCompat_SeekBar;
        public static int Widget_AppCompat_SeekBar_Discrete;
        public static int Widget_AppCompat_Spinner;
        public static int Widget_AppCompat_Spinner_DropDown;
        public static int Widget_AppCompat_Spinner_DropDown_ActionBar;
        public static int Widget_AppCompat_Spinner_Underlined;
        public static int Widget_AppCompat_TextView;
        public static int Widget_AppCompat_TextView_SpinnerItem;
        public static int Widget_AppCompat_Toolbar;
        public static int Widget_AppCompat_Toolbar_Button_Navigation;
        public static int Widget_Compat_NotificationActionContainer;
        public static int Widget_Compat_NotificationActionText;

        private style() {
        }
    }

    /* renamed from: com.trilliumeng.android.orion.orionsdklibrary.R$styleable */
    public static final class styleable {
        public static int[] ActionBar = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        public static int[] ActionBarLayout = {16842931};
        public static int ActionBarLayout_android_layout_gravity = 0;
        public static int ActionBar_background = 0;
        public static int ActionBar_backgroundSplit = 1;
        public static int ActionBar_backgroundStacked = 2;
        public static int ActionBar_contentInsetEnd = 3;
        public static int ActionBar_contentInsetEndWithActions = 4;
        public static int ActionBar_contentInsetLeft = 5;
        public static int ActionBar_contentInsetRight = 6;
        public static int ActionBar_contentInsetStart = 7;
        public static int ActionBar_contentInsetStartWithNavigation = 8;
        public static int ActionBar_customNavigationLayout = 9;
        public static int ActionBar_displayOptions = 10;
        public static int ActionBar_divider = 11;
        public static int ActionBar_elevation = 12;
        public static int ActionBar_height = 13;
        public static int ActionBar_hideOnContentScroll = 14;
        public static int ActionBar_homeAsUpIndicator = 15;
        public static int ActionBar_homeLayout = 16;
        public static int ActionBar_icon = 17;
        public static int ActionBar_indeterminateProgressStyle = 18;
        public static int ActionBar_itemPadding = 19;
        public static int ActionBar_logo = 20;
        public static int ActionBar_navigationMode = 21;
        public static int ActionBar_popupTheme = 22;
        public static int ActionBar_progressBarPadding = 23;
        public static int ActionBar_progressBarStyle = 24;
        public static int ActionBar_subtitle = 25;
        public static int ActionBar_subtitleTextStyle = 26;
        public static int ActionBar_title = 27;
        public static int ActionBar_titleTextStyle = 28;
        public static int[] ActionMenuItemView = {16843071};
        public static int ActionMenuItemView_android_minWidth = 0;
        public static int[] ActionMenuView = new int[0];
        public static int[] ActionMode = {0, 0, 0, 0, 0, 0};
        public static int ActionMode_background = 0;
        public static int ActionMode_backgroundSplit = 1;
        public static int ActionMode_closeItemLayout = 2;
        public static int ActionMode_height = 3;
        public static int ActionMode_subtitleTextStyle = 4;
        public static int ActionMode_titleTextStyle = 5;
        public static int[] ActivityChooserView = {0, 0};
        public static int ActivityChooserView_expandActivityOverflowButtonDrawable = 0;
        public static int ActivityChooserView_initialActivityCount = 1;
        public static int[] AlertDialog = {16842994, 0, 0, 0, 0, 0, 0, 0};
        public static int AlertDialog_android_layout = 0;
        public static int AlertDialog_buttonIconDimen = 1;
        public static int AlertDialog_buttonPanelSideLayout = 2;
        public static int AlertDialog_listItemLayout = 3;
        public static int AlertDialog_listLayout = 4;
        public static int AlertDialog_multiChoiceItemLayout = 5;
        public static int AlertDialog_showTitle = 6;
        public static int AlertDialog_singleChoiceItemLayout = 7;
        public static int[] AnimatedStateListDrawableCompat = {16843158, 16843036, 16843532, 16843533, 16843157, 16843156};
        public static int AnimatedStateListDrawableCompat_android_constantSize = 0;
        public static int AnimatedStateListDrawableCompat_android_dither = 1;
        public static int AnimatedStateListDrawableCompat_android_enterFadeDuration = 2;
        public static int AnimatedStateListDrawableCompat_android_exitFadeDuration = 3;
        public static int AnimatedStateListDrawableCompat_android_variablePadding = 4;
        public static int AnimatedStateListDrawableCompat_android_visible = 5;
        public static int[] AnimatedStateListDrawableItem = {16843161, 16842960};
        public static int AnimatedStateListDrawableItem_android_drawable = 0;
        public static int AnimatedStateListDrawableItem_android_id = 1;
        public static int[] AnimatedStateListDrawableTransition = {16843161, 16843850, 16843851, 16843849};
        public static int AnimatedStateListDrawableTransition_android_drawable = 0;
        public static int AnimatedStateListDrawableTransition_android_fromId = 1;
        public static int AnimatedStateListDrawableTransition_android_reversible = 2;
        public static int AnimatedStateListDrawableTransition_android_toId = 3;
        public static int[] AppCompatImageView = {16843033, 0, 0, 0};
        public static int AppCompatImageView_android_src = 0;
        public static int AppCompatImageView_srcCompat = 1;
        public static int AppCompatImageView_tint = 2;
        public static int AppCompatImageView_tintMode = 3;
        public static int[] AppCompatSeekBar = {16843074, 0, 0, 0};
        public static int AppCompatSeekBar_android_thumb = 0;
        public static int AppCompatSeekBar_tickMark = 1;
        public static int AppCompatSeekBar_tickMarkTint = 2;
        public static int AppCompatSeekBar_tickMarkTintMode = 3;
        public static int[] AppCompatTextHelper = {16843118, 16843667, 16843119, 16843120, 16843666, 16843117, 16842804};
        public static int AppCompatTextHelper_android_drawableBottom = 0;
        public static int AppCompatTextHelper_android_drawableEnd = 1;
        public static int AppCompatTextHelper_android_drawableLeft = 2;
        public static int AppCompatTextHelper_android_drawableRight = 3;
        public static int AppCompatTextHelper_android_drawableStart = 4;
        public static int AppCompatTextHelper_android_drawableTop = 5;
        public static int AppCompatTextHelper_android_textAppearance = 6;
        public static int[] AppCompatTextView = {16842804, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        public static int AppCompatTextView_android_textAppearance = 0;
        public static int AppCompatTextView_autoSizeMaxTextSize = 1;
        public static int AppCompatTextView_autoSizeMinTextSize = 2;
        public static int AppCompatTextView_autoSizePresetSizes = 3;
        public static int AppCompatTextView_autoSizeStepGranularity = 4;
        public static int AppCompatTextView_autoSizeTextType = 5;
        public static int AppCompatTextView_drawableBottomCompat = 6;
        public static int AppCompatTextView_drawableEndCompat = 7;
        public static int AppCompatTextView_drawableLeftCompat = 8;
        public static int AppCompatTextView_drawableRightCompat = 9;
        public static int AppCompatTextView_drawableStartCompat = 10;
        public static int AppCompatTextView_drawableTint = 11;
        public static int AppCompatTextView_drawableTintMode = 12;
        public static int AppCompatTextView_drawableTopCompat = 13;
        public static int AppCompatTextView_firstBaselineToTopHeight = 14;
        public static int AppCompatTextView_fontFamily = 15;
        public static int AppCompatTextView_fontVariationSettings = 16;
        public static int AppCompatTextView_lastBaselineToBottomHeight = 17;
        public static int AppCompatTextView_lineHeight = 18;
        public static int AppCompatTextView_textAllCaps = 19;
        public static int AppCompatTextView_textLocale = 20;
        public static int[] AppCompatTheme = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16842926, 16842839, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        public static int AppCompatTheme_actionBarDivider = 0;
        public static int AppCompatTheme_actionBarItemBackground = 1;
        public static int AppCompatTheme_actionBarPopupTheme = 2;
        public static int AppCompatTheme_actionBarSize = 3;
        public static int AppCompatTheme_actionBarSplitStyle = 4;
        public static int AppCompatTheme_actionBarStyle = 5;
        public static int AppCompatTheme_actionBarTabBarStyle = 6;
        public static int AppCompatTheme_actionBarTabStyle = 7;
        public static int AppCompatTheme_actionBarTabTextStyle = 8;
        public static int AppCompatTheme_actionBarTheme = 9;
        public static int AppCompatTheme_actionBarWidgetTheme = 10;
        public static int AppCompatTheme_actionButtonStyle = 11;
        public static int AppCompatTheme_actionDropDownStyle = 12;
        public static int AppCompatTheme_actionMenuTextAppearance = 13;
        public static int AppCompatTheme_actionMenuTextColor = 14;
        public static int AppCompatTheme_actionModeBackground = 15;
        public static int AppCompatTheme_actionModeCloseButtonStyle = 16;
        public static int AppCompatTheme_actionModeCloseDrawable = 17;
        public static int AppCompatTheme_actionModeCopyDrawable = 18;
        public static int AppCompatTheme_actionModeCutDrawable = 19;
        public static int AppCompatTheme_actionModeFindDrawable = 20;
        public static int AppCompatTheme_actionModePasteDrawable = 21;
        public static int AppCompatTheme_actionModePopupWindowStyle = 22;
        public static int AppCompatTheme_actionModeSelectAllDrawable = 23;
        public static int AppCompatTheme_actionModeShareDrawable = 24;
        public static int AppCompatTheme_actionModeSplitBackground = 25;
        public static int AppCompatTheme_actionModeStyle = 26;
        public static int AppCompatTheme_actionModeWebSearchDrawable = 27;
        public static int AppCompatTheme_actionOverflowButtonStyle = 28;
        public static int AppCompatTheme_actionOverflowMenuStyle = 29;
        public static int AppCompatTheme_activityChooserViewStyle = 30;
        public static int AppCompatTheme_alertDialogButtonGroupStyle = 31;
        public static int AppCompatTheme_alertDialogCenterButtons = 32;
        public static int AppCompatTheme_alertDialogStyle = 33;
        public static int AppCompatTheme_alertDialogTheme = 34;
        public static int AppCompatTheme_android_windowAnimationStyle = 35;
        public static int AppCompatTheme_android_windowIsFloating = 36;
        public static int AppCompatTheme_autoCompleteTextViewStyle = 37;
        public static int AppCompatTheme_borderlessButtonStyle = 38;
        public static int AppCompatTheme_buttonBarButtonStyle = 39;
        public static int AppCompatTheme_buttonBarNegativeButtonStyle = 40;
        public static int AppCompatTheme_buttonBarNeutralButtonStyle = 41;
        public static int AppCompatTheme_buttonBarPositiveButtonStyle = 42;
        public static int AppCompatTheme_buttonBarStyle = 43;
        public static int AppCompatTheme_buttonStyle = 44;
        public static int AppCompatTheme_buttonStyleSmall = 45;
        public static int AppCompatTheme_checkboxStyle = 46;
        public static int AppCompatTheme_checkedTextViewStyle = 47;
        public static int AppCompatTheme_colorAccent = 48;
        public static int AppCompatTheme_colorBackgroundFloating = 49;
        public static int AppCompatTheme_colorButtonNormal = 50;
        public static int AppCompatTheme_colorControlActivated = 51;
        public static int AppCompatTheme_colorControlHighlight = 52;
        public static int AppCompatTheme_colorControlNormal = 53;
        public static int AppCompatTheme_colorError = 54;
        public static int AppCompatTheme_colorPrimary = 55;
        public static int AppCompatTheme_colorPrimaryDark = 56;
        public static int AppCompatTheme_colorSwitchThumbNormal = 57;
        public static int AppCompatTheme_controlBackground = 58;
        public static int AppCompatTheme_dialogCornerRadius = 59;
        public static int AppCompatTheme_dialogPreferredPadding = 60;
        public static int AppCompatTheme_dialogTheme = 61;
        public static int AppCompatTheme_dividerHorizontal = 62;
        public static int AppCompatTheme_dividerVertical = 63;
        public static int AppCompatTheme_dropDownListViewStyle = 64;
        public static int AppCompatTheme_dropdownListPreferredItemHeight = 65;
        public static int AppCompatTheme_editTextBackground = 66;
        public static int AppCompatTheme_editTextColor = 67;
        public static int AppCompatTheme_editTextStyle = 68;
        public static int AppCompatTheme_homeAsUpIndicator = 69;
        public static int AppCompatTheme_imageButtonStyle = 70;
        public static int AppCompatTheme_listChoiceBackgroundIndicator = 71;
        public static int AppCompatTheme_listChoiceIndicatorMultipleAnimated = 72;
        public static int AppCompatTheme_listChoiceIndicatorSingleAnimated = 73;
        public static int AppCompatTheme_listDividerAlertDialog = 74;
        public static int AppCompatTheme_listMenuViewStyle = 75;
        public static int AppCompatTheme_listPopupWindowStyle = 76;
        public static int AppCompatTheme_listPreferredItemHeight = 77;
        public static int AppCompatTheme_listPreferredItemHeightLarge = 78;
        public static int AppCompatTheme_listPreferredItemHeightSmall = 79;
        public static int AppCompatTheme_listPreferredItemPaddingEnd = 80;
        public static int AppCompatTheme_listPreferredItemPaddingLeft = 81;
        public static int AppCompatTheme_listPreferredItemPaddingRight = 82;
        public static int AppCompatTheme_listPreferredItemPaddingStart = 83;
        public static int AppCompatTheme_panelBackground = 84;
        public static int AppCompatTheme_panelMenuListTheme = 85;
        public static int AppCompatTheme_panelMenuListWidth = 86;
        public static int AppCompatTheme_popupMenuStyle = 87;
        public static int AppCompatTheme_popupWindowStyle = 88;
        public static int AppCompatTheme_radioButtonStyle = 89;
        public static int AppCompatTheme_ratingBarStyle = 90;
        public static int AppCompatTheme_ratingBarStyleIndicator = 91;
        public static int AppCompatTheme_ratingBarStyleSmall = 92;
        public static int AppCompatTheme_searchViewStyle = 93;
        public static int AppCompatTheme_seekBarStyle = 94;
        public static int AppCompatTheme_selectableItemBackground = 95;
        public static int AppCompatTheme_selectableItemBackgroundBorderless = 96;
        public static int AppCompatTheme_spinnerDropDownItemStyle = 97;
        public static int AppCompatTheme_spinnerStyle = 98;
        public static int AppCompatTheme_switchStyle = 99;
        public static int AppCompatTheme_textAppearanceLargePopupMenu = 100;
        public static int AppCompatTheme_textAppearanceListItem = 101;
        public static int AppCompatTheme_textAppearanceListItemSecondary = 102;
        public static int AppCompatTheme_textAppearanceListItemSmall = 103;
        public static int AppCompatTheme_textAppearancePopupMenuHeader = 104;
        public static int AppCompatTheme_textAppearanceSearchResultSubtitle = 105;
        public static int AppCompatTheme_textAppearanceSearchResultTitle = 106;
        public static int AppCompatTheme_textAppearanceSmallPopupMenu = 107;
        public static int AppCompatTheme_textColorAlertDialogListItem = 108;
        public static int AppCompatTheme_textColorSearchUrl = 109;
        public static int AppCompatTheme_toolbarNavigationButtonStyle = 110;
        public static int AppCompatTheme_toolbarStyle = 111;
        public static int AppCompatTheme_tooltipForegroundColor = 112;
        public static int AppCompatTheme_tooltipFrameBackground = 113;
        public static int AppCompatTheme_viewInflaterClass = 114;
        public static int AppCompatTheme_windowActionBar = 115;
        public static int AppCompatTheme_windowActionBarOverlay = 116;
        public static int AppCompatTheme_windowActionModeOverlay = 117;
        public static int AppCompatTheme_windowFixedHeightMajor = 118;
        public static int AppCompatTheme_windowFixedHeightMinor = 119;
        public static int AppCompatTheme_windowFixedWidthMajor = 120;
        public static int AppCompatTheme_windowFixedWidthMinor = 121;
        public static int AppCompatTheme_windowMinWidthMajor = 122;
        public static int AppCompatTheme_windowMinWidthMinor = 123;
        public static int AppCompatTheme_windowNoTitle = 124;
        public static int[] ButtonBarLayout = {0};
        public static int ButtonBarLayout_allowStacking = 0;
        public static int[] ColorStateListItem = {0, 16843551, 16843173};
        public static int ColorStateListItem_alpha = 0;
        public static int ColorStateListItem_android_alpha = 1;
        public static int ColorStateListItem_android_color = 2;
        public static int[] CompoundButton = {16843015, 0, 0, 0};
        public static int CompoundButton_android_button = 0;
        public static int CompoundButton_buttonCompat = 1;
        public static int CompoundButton_buttonTint = 2;
        public static int CompoundButton_buttonTintMode = 3;
        public static int[] DrawerArrowToggle = {0, 0, 0, 0, 0, 0, 0, 0};
        public static int DrawerArrowToggle_arrowHeadLength = 0;
        public static int DrawerArrowToggle_arrowShaftLength = 1;
        public static int DrawerArrowToggle_barLength = 2;
        public static int DrawerArrowToggle_color = 3;
        public static int DrawerArrowToggle_drawableSize = 4;
        public static int DrawerArrowToggle_gapBetweenBars = 5;
        public static int DrawerArrowToggle_spinBars = 6;
        public static int DrawerArrowToggle_thickness = 7;
        public static int[] FontFamily = {0, 0, 0, 0, 0, 0};
        public static int[] FontFamilyFont = {16844082, 16844095, 16844144, 16844083, 16844143, 0, 0, 0, 0, 0};
        public static int FontFamilyFont_android_font = 0;
        public static int FontFamilyFont_android_fontStyle = 1;
        public static int FontFamilyFont_android_fontVariationSettings = 2;
        public static int FontFamilyFont_android_fontWeight = 3;
        public static int FontFamilyFont_android_ttcIndex = 4;
        public static int FontFamilyFont_font = 5;
        public static int FontFamilyFont_fontStyle = 6;
        public static int FontFamilyFont_fontVariationSettings = 7;
        public static int FontFamilyFont_fontWeight = 8;
        public static int FontFamilyFont_ttcIndex = 9;
        public static int FontFamily_fontProviderAuthority = 0;
        public static int FontFamily_fontProviderCerts = 1;
        public static int FontFamily_fontProviderFetchStrategy = 2;
        public static int FontFamily_fontProviderFetchTimeout = 3;
        public static int FontFamily_fontProviderPackage = 4;
        public static int FontFamily_fontProviderQuery = 5;
        public static int[] GradientColor = {16843275, 16843170, 16843171, 16843166, 16844050, 16844051, 16843172, 16843165, 16844048, 16844049, 16843265, 16843169};
        public static int[] GradientColorItem = {16843173, 16844052};
        public static int GradientColorItem_android_color = 0;
        public static int GradientColorItem_android_offset = 1;
        public static int GradientColor_android_centerColor = 0;
        public static int GradientColor_android_centerX = 1;
        public static int GradientColor_android_centerY = 2;
        public static int GradientColor_android_endColor = 3;
        public static int GradientColor_android_endX = 4;
        public static int GradientColor_android_endY = 5;
        public static int GradientColor_android_gradientRadius = 6;
        public static int GradientColor_android_startColor = 7;
        public static int GradientColor_android_startX = 8;
        public static int GradientColor_android_startY = 9;
        public static int GradientColor_android_tileMode = 10;
        public static int GradientColor_android_type = 11;
        public static int[] LinearLayoutCompat = {16843046, 16843047, 16842927, 16842948, 16843048, 0, 0, 0, 0};
        public static int[] LinearLayoutCompat_Layout = {16842931, 16842997, 16843137, 16842996};
        public static int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static int LinearLayoutCompat_Layout_android_layout_height = 1;
        public static int LinearLayoutCompat_Layout_android_layout_weight = 2;
        public static int LinearLayoutCompat_Layout_android_layout_width = 3;
        public static int LinearLayoutCompat_android_baselineAligned = 0;
        public static int LinearLayoutCompat_android_baselineAlignedChildIndex = 1;
        public static int LinearLayoutCompat_android_gravity = 2;
        public static int LinearLayoutCompat_android_orientation = 3;
        public static int LinearLayoutCompat_android_weightSum = 4;
        public static int LinearLayoutCompat_divider = 5;
        public static int LinearLayoutCompat_dividerPadding = 6;
        public static int LinearLayoutCompat_measureWithLargestChild = 7;
        public static int LinearLayoutCompat_showDividers = 8;
        public static int[] ListPopupWindow = {16843436, 16843437};
        public static int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static int[] MenuGroup = {16843232, 16842766, 16842960, 16843230, 16843231, 16843156};
        public static int MenuGroup_android_checkableBehavior = 0;
        public static int MenuGroup_android_enabled = 1;
        public static int MenuGroup_android_id = 2;
        public static int MenuGroup_android_menuCategory = 3;
        public static int MenuGroup_android_orderInCategory = 4;
        public static int MenuGroup_android_visible = 5;
        public static int[] MenuItem = {0, 0, 0, 0, 16843235, 16843237, 16843014, 16842766, 16842754, 16842960, 16843230, 16843236, 16843375, 16843231, 16843233, 16843234, 16843156, 0, 0, 0, 0, 0, 0};
        public static int MenuItem_actionLayout = 0;
        public static int MenuItem_actionProviderClass = 1;
        public static int MenuItem_actionViewClass = 2;
        public static int MenuItem_alphabeticModifiers = 3;
        public static int MenuItem_android_alphabeticShortcut = 4;
        public static int MenuItem_android_checkable = 5;
        public static int MenuItem_android_checked = 6;
        public static int MenuItem_android_enabled = 7;
        public static int MenuItem_android_icon = 8;
        public static int MenuItem_android_id = 9;
        public static int MenuItem_android_menuCategory = 10;
        public static int MenuItem_android_numericShortcut = 11;
        public static int MenuItem_android_onClick = 12;
        public static int MenuItem_android_orderInCategory = 13;
        public static int MenuItem_android_title = 14;
        public static int MenuItem_android_titleCondensed = 15;
        public static int MenuItem_android_visible = 16;
        public static int MenuItem_contentDescription = 17;
        public static int MenuItem_iconTint = 18;
        public static int MenuItem_iconTintMode = 19;
        public static int MenuItem_numericModifiers = 20;
        public static int MenuItem_showAsAction = 21;
        public static int MenuItem_tooltipText = 22;
        public static int[] MenuView = {16843055, 16843053, 16843056, 16843057, 16843052, 16843054, 16842926, 0, 0};
        public static int MenuView_android_headerBackground = 0;
        public static int MenuView_android_horizontalDivider = 1;
        public static int MenuView_android_itemBackground = 2;
        public static int MenuView_android_itemIconDisabledAlpha = 3;
        public static int MenuView_android_itemTextAppearance = 4;
        public static int MenuView_android_verticalDivider = 5;
        public static int MenuView_android_windowAnimationStyle = 6;
        public static int MenuView_preserveIconSpacing = 7;
        public static int MenuView_subMenuArrow = 8;
        public static int[] PopupWindow = {16843465, 16843126, 0};
        public static int[] PopupWindowBackgroundState = {0};
        public static int PopupWindowBackgroundState_state_above_anchor = 0;
        public static int PopupWindow_android_popupAnimationStyle = 0;
        public static int PopupWindow_android_popupBackground = 1;
        public static int PopupWindow_overlapAnchor = 2;
        public static int[] RecycleListView = {0, 0};
        public static int RecycleListView_paddingBottomNoButtons = 0;
        public static int RecycleListView_paddingTopNoTitle = 1;
        public static int[] SearchView = {16842970, 16843364, 16843296, 16843039, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        public static int SearchView_android_focusable = 0;
        public static int SearchView_android_imeOptions = 1;
        public static int SearchView_android_inputType = 2;
        public static int SearchView_android_maxWidth = 3;
        public static int SearchView_closeIcon = 4;
        public static int SearchView_commitIcon = 5;
        public static int SearchView_defaultQueryHint = 6;
        public static int SearchView_goIcon = 7;
        public static int SearchView_iconifiedByDefault = 8;
        public static int SearchView_layout = 9;
        public static int SearchView_queryBackground = 10;
        public static int SearchView_queryHint = 11;
        public static int SearchView_searchHintIcon = 12;
        public static int SearchView_searchIcon = 13;
        public static int SearchView_submitBackground = 14;
        public static int SearchView_suggestionRowLayout = 15;
        public static int SearchView_voiceIcon = 16;
        public static int[] Spinner = {16843362, 16842930, 16843126, 16843131, 0};
        public static int Spinner_android_dropDownWidth = 0;
        public static int Spinner_android_entries = 1;
        public static int Spinner_android_popupBackground = 2;
        public static int Spinner_android_prompt = 3;
        public static int Spinner_popupTheme = 4;
        public static int[] StateListDrawable = {16843158, 16843036, 16843532, 16843533, 16843157, 16843156};
        public static int[] StateListDrawableItem = {16843161};
        public static int StateListDrawableItem_android_drawable = 0;
        public static int StateListDrawable_android_constantSize = 0;
        public static int StateListDrawable_android_dither = 1;
        public static int StateListDrawable_android_enterFadeDuration = 2;
        public static int StateListDrawable_android_exitFadeDuration = 3;
        public static int StateListDrawable_android_variablePadding = 4;
        public static int StateListDrawable_android_visible = 5;
        public static int[] SwitchCompat = {16843045, 16843044, 16843074, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        public static int SwitchCompat_android_textOff = 0;
        public static int SwitchCompat_android_textOn = 1;
        public static int SwitchCompat_android_thumb = 2;
        public static int SwitchCompat_showText = 3;
        public static int SwitchCompat_splitTrack = 4;
        public static int SwitchCompat_switchMinWidth = 5;
        public static int SwitchCompat_switchPadding = 6;
        public static int SwitchCompat_switchTextAppearance = 7;
        public static int SwitchCompat_thumbTextPadding = 8;
        public static int SwitchCompat_thumbTint = 9;
        public static int SwitchCompat_thumbTintMode = 10;
        public static int SwitchCompat_track = 11;
        public static int SwitchCompat_trackTint = 12;
        public static int SwitchCompat_trackTintMode = 13;
        public static int[] TextAppearance = {16843692, 16843105, 16843106, 16843107, 16843108, 16842904, 16842906, 16842907, 16844165, 16842901, 16842903, 16842902, 0, 0, 0, 0};
        public static int TextAppearance_android_fontFamily = 0;
        public static int TextAppearance_android_shadowColor = 1;
        public static int TextAppearance_android_shadowDx = 2;
        public static int TextAppearance_android_shadowDy = 3;
        public static int TextAppearance_android_shadowRadius = 4;
        public static int TextAppearance_android_textColor = 5;
        public static int TextAppearance_android_textColorHint = 6;
        public static int TextAppearance_android_textColorLink = 7;
        public static int TextAppearance_android_textFontWeight = 8;
        public static int TextAppearance_android_textSize = 9;
        public static int TextAppearance_android_textStyle = 10;
        public static int TextAppearance_android_typeface = 11;
        public static int TextAppearance_fontFamily = 12;
        public static int TextAppearance_fontVariationSettings = 13;
        public static int TextAppearance_textAllCaps = 14;
        public static int TextAppearance_textLocale = 15;
        public static int[] Toolbar = {16842927, 16843072, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        public static int Toolbar_android_gravity = 0;
        public static int Toolbar_android_minHeight = 1;
        public static int Toolbar_buttonGravity = 2;
        public static int Toolbar_collapseContentDescription = 3;
        public static int Toolbar_collapseIcon = 4;
        public static int Toolbar_contentInsetEnd = 5;
        public static int Toolbar_contentInsetEndWithActions = 6;
        public static int Toolbar_contentInsetLeft = 7;
        public static int Toolbar_contentInsetRight = 8;
        public static int Toolbar_contentInsetStart = 9;
        public static int Toolbar_contentInsetStartWithNavigation = 10;
        public static int Toolbar_logo = 11;
        public static int Toolbar_logoDescription = 12;
        public static int Toolbar_maxButtonHeight = 13;
        public static int Toolbar_menu = 14;
        public static int Toolbar_navigationContentDescription = 15;
        public static int Toolbar_navigationIcon = 16;
        public static int Toolbar_popupTheme = 17;
        public static int Toolbar_subtitle = 18;
        public static int Toolbar_subtitleTextAppearance = 19;
        public static int Toolbar_subtitleTextColor = 20;
        public static int Toolbar_title = 21;
        public static int Toolbar_titleMargin = 22;
        public static int Toolbar_titleMarginBottom = 23;
        public static int Toolbar_titleMarginEnd = 24;
        public static int Toolbar_titleMarginStart = 25;
        public static int Toolbar_titleMarginTop = 26;
        public static int Toolbar_titleMargins = 27;
        public static int Toolbar_titleTextAppearance = 28;
        public static int Toolbar_titleTextColor = 29;
        public static int[] View = {16842970, 16842752, 0, 0, 0};
        public static int[] ViewBackgroundHelper = {16842964, 0, 0};
        public static int ViewBackgroundHelper_android_background = 0;
        public static int ViewBackgroundHelper_backgroundTint = 1;
        public static int ViewBackgroundHelper_backgroundTintMode = 2;
        public static int[] ViewStubCompat = {16842960, 16842995, 16842994};
        public static int ViewStubCompat_android_id = 0;
        public static int ViewStubCompat_android_inflatedId = 1;
        public static int ViewStubCompat_android_layout = 2;
        public static int View_android_focusable = 0;
        public static int View_android_theme = 1;
        public static int View_paddingEnd = 2;
        public static int View_paddingStart = 3;
        public static int View_theme = 4;

        private styleable() {
        }
    }

    private C5913R() {
    }
}
