package com.atakmap.android.uastool.pagers.video_ui.default_ui;

import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.Color;
import com.atakmap.android.uastool.UASToolDropDownReceiver;
import com.atakmap.android.uastool.plugin.C1877R;
import com.atakmap.android.uastool.prefs.UIPreferenceFragment;

public class UIConstants {
    public static int BUTTON_MARGIN;
    public static int BUTTON_SIZE_FULL;
    public static int BUTTON_SIZE_HALF;
    public static int BUTTON_STROKE_FULL;
    public static int BUTTON_STROKE_HALF;
    public static int COLOR_DANGER;
    public static int COLOR_DISABLED;
    public static int COLOR_ENABLED_FULL;
    public static int COLOR_ENABLED_HALF;
    public static int COLOR_ON;
    public static int COLOR_PENDING;
    public static int COLOR_PRESSED;
    public static int COLOR_TRANSPARENT;
    public static int GIMBALHEADING_TEXT_FULL;
    public static int GIMBALHEADING_TEXT_HALF;
    public static int GIMBALPITCH_PADDING_FULL;
    public static int GIMBALPITCH_PADDING_HALF;
    public static int HORIZBAR_PAD_BOTTOM;
    public static int HORIZBAR_PAD_END;
    public static int HORIZBAR_PAD_START;
    public static int HORIZBAR_PAD_TOP;
    public static int JOYSTICK_BUTTONS_BOTTOM_OFFSET_FULL;
    public static int JOYSTICK_BUTTONS_BUTTON_HEIGHT_FULL;
    public static int JOYSTICK_BUTTONS_BUTTON_MARGIN_FULL;
    public static int JOYSTICK_BUTTONS_BUTTON_WIDTH_FULL;
    public static int JOYSTICK_BUTTONS_LEFT_OFFSET_FULL;
    public static int JOYSTICK_BUTTONS_TOP_OFFSET_FULL;
    public static int JOYSTICK_LEVELS_COLOR_OFF;
    public static int JOYSTICK_LEVELS_COLOR_ON;
    public static int JOYSTICK_LEVELS_COLOR_ON_MAX;
    public static int JOYSTICK_STICKS_BOTTOM_OFFSET_FULL;
    public static int JOYSTICK_STICKS_LEFT_OFFSET_FULL;
    public static int JOYSTICK_STICKS_LIMIT_RADIUS;
    public static int JOYSTICK_STICKS_STICK_RADIUS;
    public static int JOYSTICK_STICKS_TOP_OFFSET_FULL;
    public static int PLAT_DIV_HEIGHT_FULL;
    public static int PLAT_DIV_HEIGHT_HALF;
    public static int PLAT_DIV_WIDTH_FULL;
    public static int PLAT_DIV_WIDTH_HALF;
    public static int RETICLE_SIZE_FULL_LARGE;
    public static int RETICLE_SIZE_FULL_MEDIUM;
    public static int RETICLE_SIZE_FULL_SMALL;
    public static int RETICLE_SIZE_HALF_LARGE;
    public static int RETICLE_SIZE_HALF_MEDIUM;
    public static int RETICLE_SIZE_HALF_SMALL;
    public static int TEXTSHADOW_COLOR;
    public static float TEXTSHADOW_DX;
    public static float TEXTSHADOW_DY;
    public static float TEXTSHADOW_RADIUS;
    public static int TEXT_COLOR;
    public static int TOPBAR_BATTERY_TEXT_FULL;
    public static int TOPBAR_BATTERY_TEXT_HALF;
    public static int TOPBAR_HEIGHT_FULL;
    public static int TOPBAR_HEIGHT_HALF;
    public static int UASHEADING_SIZE_FULL;
    public static int UASHEADING_SIZE_HALF;
    public static int UASHEADING_TEXT_FULL;
    public static int UASHEADING_TEXT_HALF;
    public static int VERTBAR_PAD_BOTTOM;
    public static int VERTBAR_PAD_END;
    public static int VERTBAR_PAD_START;
    public static int VERTBAR_PAD_TOP;
    public static int WIDGET_PAD_HALF;

    private void UIConstants() {
    }

    public static void init(Context context) {
        BUTTON_SIZE_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_button_size_full);
        BUTTON_SIZE_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_button_size_half);
        BUTTON_MARGIN = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_button_margin);
        BUTTON_STROKE_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_button_stroke_full);
        BUTTON_STROKE_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_button_stroke_half);
        VERTBAR_PAD_START = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_vertbar_pad_start);
        VERTBAR_PAD_TOP = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_vertbar_pad_top);
        VERTBAR_PAD_END = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_vertbar_pad_end);
        VERTBAR_PAD_BOTTOM = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_vertbar_pad_bottom);
        HORIZBAR_PAD_START = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_horizbar_pad_start);
        HORIZBAR_PAD_TOP = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_horizbar_pad_top);
        HORIZBAR_PAD_END = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_horizbar_pad_end);
        HORIZBAR_PAD_BOTTOM = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_horizbar_pad_bottom);
        PLAT_DIV_WIDTH_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_platdiv_width_full);
        PLAT_DIV_HEIGHT_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_platdiv_height_full);
        PLAT_DIV_WIDTH_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_platdiv_width_half);
        PLAT_DIV_HEIGHT_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_platdiv_height_half);
        WIDGET_PAD_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_widget_pad_half);
        COLOR_TRANSPARENT = context.getResources().getColor(C1877R.color.video_ui_transparent);
        COLOR_DISABLED = context.getResources().getColor(C1877R.color.video_ui_disabled);
        COLOR_PRESSED = context.getResources().getColor(C1877R.color.video_ui_pressed);
        COLOR_ON = context.getResources().getColor(C1877R.color.video_ui_on);
        COLOR_PENDING = context.getResources().getColor(C1877R.color.video_ui_pending);
        COLOR_DANGER = context.getResources().getColor(C1877R.color.video_ui_danger);
        COLOR_ENABLED_FULL = context.getResources().getColor(C1877R.color.video_ui_enabled_full);
        COLOR_ENABLED_HALF = context.getResources().getColor(C1877R.color.video_ui_enabled_half);
        UASHEADING_SIZE_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_uasheading_size_full);
        UASHEADING_SIZE_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_uasheading_size_half);
        UASHEADING_TEXT_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_uasheading_text_full);
        UASHEADING_TEXT_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_uasheading_text_half);
        GIMBALHEADING_TEXT_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_gimbalheading_text_full);
        GIMBALHEADING_TEXT_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_gimbalheading_text_half);
        GIMBALPITCH_PADDING_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_gimbalpitch_padding_full);
        GIMBALPITCH_PADDING_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_gimbalpitch_padding_half);
        TOPBAR_HEIGHT_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_height_full);
        TOPBAR_HEIGHT_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_height_half);
        TOPBAR_BATTERY_TEXT_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_battery_text_full);
        TOPBAR_BATTERY_TEXT_HALF = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_topbar_battery_text_half);
        JOYSTICK_BUTTONS_BUTTON_WIDTH_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_buttons_button_width_full);
        JOYSTICK_BUTTONS_BUTTON_HEIGHT_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_buttons_button_height_full);
        JOYSTICK_BUTTONS_BUTTON_MARGIN_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_buttons_button_margin);
        JOYSTICK_BUTTONS_TOP_OFFSET_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_buttons_top_offset);
        JOYSTICK_BUTTONS_BOTTOM_OFFSET_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_buttons_bottom_offset);
        JOYSTICK_BUTTONS_LEFT_OFFSET_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_buttons_left_offset);
        JOYSTICK_LEVELS_COLOR_ON = context.getResources().getColor(C1877R.color.joystick_ui_levels_on);
        JOYSTICK_LEVELS_COLOR_ON_MAX = context.getResources().getColor(C1877R.color.joystick_ui_levels_on_max);
        JOYSTICK_LEVELS_COLOR_OFF = context.getResources().getColor(C1877R.color.joystick_ui_levels_off);
        JOYSTICK_STICKS_STICK_RADIUS = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_sticks_stick_radius);
        JOYSTICK_STICKS_LIMIT_RADIUS = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_sticks_limit_radius);
        JOYSTICK_STICKS_TOP_OFFSET_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_sticks_top_offset);
        JOYSTICK_STICKS_BOTTOM_OFFSET_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_sticks_bottom_offset);
        JOYSTICK_STICKS_LEFT_OFFSET_FULL = (int) context.getResources().getDimension(C1877R.dimen.uastool_joystick_sticks_left_offset);
        RETICLE_SIZE_FULL_SMALL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_reticle_size_full_small);
        RETICLE_SIZE_FULL_MEDIUM = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_reticle_size_full_medium);
        RETICLE_SIZE_FULL_LARGE = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_reticle_size_full_large);
        RETICLE_SIZE_HALF_SMALL = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_reticle_size_half_small);
        RETICLE_SIZE_HALF_MEDIUM = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_reticle_size_half_medium);
        RETICLE_SIZE_HALF_LARGE = (int) context.getResources().getDimension(C1877R.dimen.uastool_ui_reticle_size_half_large);
        TypedArray obtainStyledAttributes = context.obtainStyledAttributes(C1877R.style.video_ui_text_style, C1877R.styleable.video_ui_text_styleable);
        try {
            TEXT_COLOR = Color.parseColor(obtainStyledAttributes.getString(0));
            TEXTSHADOW_COLOR = Color.parseColor(obtainStyledAttributes.getString(1));
            TEXTSHADOW_DX = obtainStyledAttributes.getFloat(2, 4.0f);
            TEXTSHADOW_DY = obtainStyledAttributes.getFloat(3, 4.0f);
            TEXTSHADOW_RADIUS = obtainStyledAttributes.getFloat(4, 1.0f);
        } catch (Exception e) {
            UASToolDropDownReceiver.toast("UIConstants Exception: " + e.getLocalizedMessage());
            e.printStackTrace();
            TEXT_COLOR = Color.parseColor(UIPreferenceFragment.DEFAULT_OSD_TEXT_COLOR);
            TEXTSHADOW_COLOR = Color.parseColor(UIPreferenceFragment.DEFAULT_OSD_BACKGROUND_COLOR);
            TEXTSHADOW_DX = 4.0f;
            TEXTSHADOW_DY = 4.0f;
            TEXTSHADOW_RADIUS = 1.0f;
        }
        obtainStyledAttributes.recycle();
    }
}
