package com.autel.common.remotecontroller;

public enum RemoteControllerNavigateButtonEvent {
    START_VIDEO,
    START_VIDEO_WITH_FOCUS,
    TAKEN_PHOTO,
    TAKEN_PHOTO_WITH_FOCUS,
    CUSTOM_BUTTON_CLICK,
    CUSTOM_WHEEL_LEFT_SLIDE,
    CUSTOM_WHEEL_RIGHT_SLIDE,
    CUSTOM_WHEEL_CLICK,
    CUSTOM_BUTTON_SHORT_A,
    CUSTOM_BUTTON_LONG_A,
    CUSTOM_BUTTON_SHORT_B,
    CUSTOM_BUTTON_LONG_B,
    UNKNOWN
}
